steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE_URI}
      - .

images:
  - ${_IMAGE_URI}

serviceAccount: projects/$PROJECT_ID/serviceAccounts/699017940678-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
