(function(){
'use strict';
const WINDOW_ID='panthorium-dual-ai-dashboard';
function os(){try{return typeof OS!=='undefined'?OS:null;}catch(_){return null;}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function allowed(){return window.PanthoriumAuth?.hasPermission?.('settings')===true;}
function notify(message){if(typeof toast==='function')toast(message);else console.log('[DualAI]',message);}
async function refreshToken(){const s=os();if(s?.config?.accessToken)return s.config.accessToken;if(window.PanthoriumAuth?.refreshSession){const ok=await window.PanthoriumAuth.refreshSession().catch(()=>false);if(ok)return os()?.config?.accessToken||'';}return'';}
async function api(path,options={},retry=true){let token=os()?.config?.accessToken||'';if(!token)token=await refreshToken();const headers={...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers,credentials:'include'});const data=await response.json().catch(()=>({}));if(response.status===401&&retry&&window.PanthoriumAuth?.refreshSession){const ok=await window.PanthoriumAuth.refreshSession().catch(()=>false);if(ok)return api(path,options,false);}if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;}
function fmt(value){if(!value)return'-';try{return new Date(value).toLocaleString('th-TH');}catch(_){return String(value);}}
function ensureStyle(){if(document.getElementById('panthorium-dual-ai-style'))return;const style=document.createElement('style');style.id='panthorium-dual-ai-style';style.textContent=`
#${WINDOW_ID}{position:fixed;inset:5%;z-index:10090;background:#06101d;color:#e8f8ff;border:1px solid #31506a;border-radius:18px;box-shadow:0 32px 100px rgba(0,0,0,.7);display:flex;flex-direction:column;overflow:hidden}
#${WINDOW_ID} .dai-head{padding:14px 18px;border-bottom:1px solid #22384f;display:flex;align-items:center;justify-content:space-between;gap:12px;background:linear-gradient(135deg,#071827,#112238)}
#${WINDOW_ID} .dai-title{font-weight:900;font-size:16px}#${WINDOW_ID} .dai-body{padding:16px;overflow:auto;display:grid;gap:14px}#${WINDOW_ID} .dai-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}#${WINDOW_ID} .dai-card{background:#0d1d2d;border:1px solid #25405a;border-radius:12px;padding:12px;min-height:80px}#${WINDOW_ID} .dai-label{font-size:11px;color:#9db6ca}#${WINDOW_ID} .dai-value{font-size:21px;font-weight:900;color:#86ffdd;margin-top:5px;word-break:break-word}#${WINDOW_ID} .dai-section{background:#081827;border:1px solid #1c3148;border-radius:12px;padding:12px}#${WINDOW_ID} .dai-row{display:grid;grid-template-columns:150px 90px 1fr;gap:8px;align-items:start;border-bottom:1px solid rgba(255,255,255,.06);padding:8px 0;font-size:12px}#${WINDOW_ID} .dai-row:last-child{border-bottom:0}#${WINDOW_ID} .dai-muted{color:#9db6ca;font-size:12px}#${WINDOW_ID} .dai-actions{display:flex;gap:8px;flex-wrap:wrap}#${WINDOW_ID} button{border:1px solid #31506a;background:#0d1d2d;color:#dffcff;border-radius:9px;padding:8px 11px;cursor:pointer}#${WINDOW_ID} button:hover{border-color:#00d9b7}#${WINDOW_ID} button.dai-primary{border-color:#00d9b7;background:#073c3a}#${WINDOW_ID} button.dai-danger{border-color:#7f2c3e;background:#25101a;color:#ffd9df}.dai-badge{display:inline-flex;padding:5px 9px;border-radius:999px;border:1px solid #31506a;font-size:11px;font-weight:900}.dai-observe,.dai-healthy{color:#86ffdd;border-color:#1f8f69;background:#08261f}.dai-improving{color:#ffd77a;border-color:#806a29;background:#261f0a}.dai-critical,.dai-autopilot{color:#ff9aad;border-color:#7f2c3e;background:#25101a}.dai-off{color:#b5c2cf;background:#131b25}@media(max-width:720px){#${WINDOW_ID}{inset:0;border-radius:0}#${WINDOW_ID} .dai-row{grid-template-columns:1fr}#${WINDOW_ID} .dai-value{font-size:18px}}
`;document.head.appendChild(style);}
function badge(v){const s=String(v||'unknown');return `<span class="dai-badge dai-${esc(s)}">${esc(s.toUpperCase())}</span>`;}
function card(label,value,sub){return `<div class="dai-card"><div class="dai-label">${esc(label)}</div><div class="dai-value">${esc(value)}</div>${sub?`<div class="dai-muted">${esc(sub)}</div>`:''}</div>`;}
function profileRows(profiles){return Object.values(profiles||{}).map(p=>`<div class="dai-row"><b>${esc(p.label)}</b><div>${esc(p.audience)}</div><div>${esc(p.mission)}<br><span class="dai-muted">can: ${(p.capabilities||[]).map(esc).join(', ')}</span><br><span class="dai-muted">boundary: ${(p.boundaries||[]).map(esc).join(', ')}</span></div></div>`).join('');}
function patternRows(items){return (items||[]).map(p=>`<div class="dai-row"><b>${esc(p.label)}</b><div>${esc((p.appliedTo||[]).join(', '))}</div><div>${esc(p.implementation)}</div></div>`).join('');}
function proposalRows(items,executed){if(!items?.length)return'<div class="dai-muted">ยังไม่มี proposal</div>';const byId=new Map((executed||[]).map(e=>[e.proposalId,e]));return items.map(p=>{const e=byId.get(p.id);return `<div class="dai-row"><b>${esc(p.id)}</b><div>${esc(p.risk)}</div><div>${esc(p.reason)}${e?`<br><span class="dai-muted">executed: ${e.ok?'ok':'failed'} ${e.error?`· ${esc(e.error)}`:''}</span>`:''}</div></div>`;}).join('');}
function historyRows(items){if(!items?.length)return'<div class="dai-muted">ยังไม่มี cycle history</div>';return items.map(h=>`<div class="dai-row"><b>${esc(h.status)}</b><div>${esc(h.score)}</div><div>${esc(h.cycleId||'-')}<br><span class="dai-muted">${esc(fmt(h.startedAt))} · mode ${esc(h.mode)} · scope ${esc(h.scope)}</span></div></div>`).join('');}
function render(root,data){const b=root.querySelector('.dai-body');const last=data.lastCycle||{};const sentinel=last.sentinelState||{};const core=last.coreState||{};b.innerHTML=`
<div class="dai-grid">${card('Dual AI mode',data.mode,data.running?'24h loop running':'loop stopped')}${card('Current cycle',last.status||'none',last.score!=null?`score ${last.score}`:'no cycle yet')}${card('Sentinel Core',core.governanceStatus||'observe',`providers ${core.providerCount??data.providers?.length??0}`)}${card('Sentinel',sentinel.benchmark?.score??'-',`active learning ${sentinel.activeLearningRunning?'running':'stopped'}`)}${card('Release Gate',core.releaseGateMergeAllowed===true?'MERGE READY':core.releaseGateMergeAllowed===false?'BLOCKED':'-',`production ${core.productionStatus||'-'}`)}${card('Providers',(data.providers||[]).length,(data.providers||[]).join(', ')||'none')}</div>
<div class="dai-section"><div class="dai-actions"><button id="dai-refresh" class="dai-primary">ตรวจตอนนี้</button><button id="dai-cycle">รัน Cycle แบบ Observe</button><button id="dai-execute" class="dai-danger">รัน Cycle + Safe Execute</button><button id="dai-observe">Mode: observe</button><button id="dai-auto" class="dai-danger">Mode: autopilot</button><button id="dai-off">Mode: off</button></div><div class="dai-muted" style="margin-top:8px">สถาปัตยกรรมนี้แยก Sentinel Core สำหรับหลังบ้านและ Sentinel สำหรับผู้ใช้ทั่วไป Core สามารถจัดการผ่าน guardrails เท่านั้น ไม่ merge/deploy/bypass gate เอง</div></div>
<div class="dai-section"><h3>AI Profiles</h3>${profileRows(data.profiles)}</div>
<div class="dai-section"><h3>Frontier Architecture Patterns ที่นำมาประยุกต์</h3>${patternRows(data.architecturePatterns)}</div>
<div class="dai-section"><h3>Latest Proposals / Executed</h3>${proposalRows(last.proposals,last.executed)}</div>
<div class="dai-section"><h3>History</h3>${historyRows(data.history)}</div>`;
root.querySelector('#dai-refresh').onclick=()=>load(root);root.querySelector('#dai-cycle').onclick=()=>cycle(root,false);root.querySelector('#dai-execute').onclick=()=>cycle(root,true);root.querySelector('#dai-observe').onclick=()=>setMode(root,'observe');root.querySelector('#dai-auto').onclick=()=>setMode(root,'autopilot');root.querySelector('#dai-off').onclick=()=>setMode(root,'off');}
async function load(root){const b=root.querySelector('.dai-body');b.innerHTML='<div class="dai-muted">กำลังโหลด Dual AI Control Plane...</div>';try{render(root,await api('/api/dual-ai/status'));}catch(error){b.innerHTML=`<div style="color:#ff9aad">Dual AI unavailable: ${esc(error.message)}</div>`;}}
async function cycle(root,execute){try{await api('/api/dual-ai/cycle',{method:'POST',body:JSON.stringify({execute,source:execute?'ui-safe-execute':'ui-observe'})});notify(execute?'Dual AI safe execute cycle completed':'Dual AI observe cycle completed');load(root);}catch(error){notify('Dual AI cycle failed: '+error.message);}}
async function setMode(root,mode){try{await api('/api/dual-ai/mode',{method:'POST',body:JSON.stringify({mode})});notify(`Dual AI mode: ${mode}`);load(root);}catch(error){notify('เปลี่ยน Dual AI mode ไม่สำเร็จ: '+error.message);}}
function open(){if(!allowed())return notify('ต้องเป็น Admin จึงเปิด Dual AI ได้');ensureStyle();let root=document.getElementById(WINDOW_ID);if(root){root.style.display='flex';load(root);return;}root=document.createElement('div');root.id=WINDOW_ID;root.innerHTML='<div class="dai-head"><div><div class="dai-title">♊ Dual AI Control Plane</div><div class="dai-muted">Phase 14 · Sentinel Core + Sentinel · 24h self-improvement loop</div></div><button id="dai-close">×</button></div><div class="dai-body"></div>';document.body.appendChild(root);root.querySelector('#dai-close').onclick=()=>{root.style.display='none';};load(root);}
window.PanthoriumDualAI={open,refresh:()=>{const root=document.getElementById(WINDOW_ID);if(root)load(root);}};
})();
