(function(){
'use strict';
const WINDOW_ID='panthorium-governance-dashboard';
function os(){try{return typeof OS!=='undefined'?OS:null;}catch(_){return null;}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function allowed(){return window.PanthoriumAuth?.hasPermission?.('settings')===true;}
function notify(message){if(typeof toast==='function')toast(message);else console.log('[Governance]',message);}
async function refreshToken(){const s=os();if(s?.config?.accessToken)return s.config.accessToken;if(window.PanthoriumAuth?.refreshSession){const ok=await window.PanthoriumAuth.refreshSession().catch(()=>false);if(ok)return os()?.config?.accessToken||'';}return'';}
async function api(path,options={},retry=true){let token=os()?.config?.accessToken||'';if(!token)token=await refreshToken();const headers={...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers,credentials:'include'});const data=await response.json().catch(()=>({}));if(response.status===401&&retry&&window.PanthoriumAuth?.refreshSession){const ok=await window.PanthoriumAuth.refreshSession().catch(()=>false);if(ok)return api(path,options,false);}if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;}
function fmt(value){if(!value)return'-';try{return new Date(value).toLocaleString('th-TH');}catch(_){return String(value);}}
function badge(status){const s=String(status||'unknown');return `<span class="gov-badge gov-${esc(s)}">${esc(s.toUpperCase())}</span>`;}
function ensureStyle(){if(document.getElementById('panthorium-governance-style'))return;const style=document.createElement('style');style.id='panthorium-governance-style';style.textContent=`
#${WINDOW_ID}{position:fixed;inset:6%;z-index:10080;background:#07111e;color:#e8f8ff;border:1px solid #31506a;border-radius:18px;box-shadow:0 30px 90px rgba(0,0,0,.68);display:flex;flex-direction:column;overflow:hidden}
#${WINDOW_ID} .gov-head{padding:14px 18px;border-bottom:1px solid #22384f;display:flex;justify-content:space-between;align-items:center;gap:12px;background:linear-gradient(135deg,#081827,#0c2433)}
#${WINDOW_ID} .gov-title{font-weight:900;font-size:16px}#${WINDOW_ID} .gov-body{padding:16px;overflow:auto;display:grid;gap:14px}#${WINDOW_ID} .gov-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px}
#${WINDOW_ID} .gov-card{background:#0d1d2d;border:1px solid #25405a;border-radius:12px;padding:12px;min-height:74px}#${WINDOW_ID} .gov-label{font-size:11px;color:#9db6ca}#${WINDOW_ID} .gov-value{font-size:22px;font-weight:900;color:#86ffdd;margin-top:5px;word-break:break-word}
#${WINDOW_ID} .gov-badge{display:inline-flex;align-items:center;padding:5px 9px;border:1px solid #31506a;border-radius:999px;font-weight:900;font-size:11px}.gov-healthy,.gov-observe,.gov-open{color:#86ffdd;border-color:#1f8f69;background:#08261f}.gov-warning{color:#ffe28a;border-color:#806a29;background:#261f0a}.gov-degraded{color:#ffbc7a;border-color:#875122;background:#2a1607}.gov-critical,.gov-autopilot{color:#ff9aad;border-color:#7f2c3e;background:#25101a}.gov-off,.gov-resolved{color:#b5c2cf;background:#131b25}
#${WINDOW_ID} .gov-section{background:#081827;border:1px solid #1c3148;border-radius:12px;padding:12px}#${WINDOW_ID} .gov-row{display:grid;grid-template-columns:130px 90px 1fr auto;gap:8px;align-items:start;border-bottom:1px solid rgba(255,255,255,.06);padding:8px 0;font-size:12px}#${WINDOW_ID} .gov-row:last-child{border-bottom:0}#${WINDOW_ID} .gov-muted{color:#9db6ca;font-size:12px}#${WINDOW_ID} .gov-actions{display:flex;gap:8px;flex-wrap:wrap}#${WINDOW_ID} button{border:1px solid #31506a;background:#0d1d2d;color:#dffcff;border-radius:9px;padding:8px 11px;cursor:pointer}#${WINDOW_ID} button:hover{border-color:#00d9b7}#${WINDOW_ID} button.gov-primary{border-color:#00d9b7;background:#073c3a}#${WINDOW_ID} button.gov-danger{border-color:#7f2c3e;background:#25101a;color:#ffd9df}.gov-runbook{margin-top:6px;color:#cdefff;font-size:11px;line-height:1.4}
@media(max-width:720px){#${WINDOW_ID}{inset:0;border-radius:0}#${WINDOW_ID} .gov-row{grid-template-columns:1fr}#${WINDOW_ID} .gov-value{font-size:18px}}
`;document.head.appendChild(style);}
function card(label,value,sub){return `<div class="gov-card"><div class="gov-label">${esc(label)}</div><div class="gov-value">${esc(value)}</div>${sub?`<div class="gov-muted">${esc(sub)}</div>`:''}</div>`;}
function signalRows(items){if(!items?.length)return'<div class="gov-muted">ไม่มี active governance signal</div>';return items.map(s=>`<div class="gov-row"><b>${esc(s.code)}</b><div>${badge(s.severity)}</div><div>${esc(s.message)}<br><span class="gov-muted">${esc(fmt(s.detectedAt))}</span></div><span></span></div>`).join('');}
function actionRows(items,executed){if(!items?.length)return'<div class="gov-muted">ไม่มี action</div>';const byId=new Map((executed||[]).map(e=>[e.actionId,e]));return items.map(a=>{const e=byId.get(a.id);return `<div class="gov-row"><b>${esc(a.id)}</b><div>${esc(a.risk)}</div><div>${esc(a.reason)}${e?`<br><span class="gov-muted">executed: ${e.ok?'ok':'failed'} ${e.error?`· ${esc(e.error)}`:''}</span>`:''}</div><span></span></div>`;}).join('');}
function incidentRows(items){if(!items?.length)return'<div class="gov-muted">ไม่มี incident เปิดอยู่</div>';return items.map(i=>{const steps=(i.runbook?.steps||[]).slice(0,4).map(step=>`• ${esc(step)}`).join('<br>');return `<div class="gov-row"><b>${esc(i.code)}</b><div>${badge(i.severity)}<br>${badge(i.status)}</div><div>occurrences ${esc(i.occurrences||1)} · last ${esc(fmt(i.lastSeenAt))}<div class="gov-runbook">${steps||esc(i.runbook?.safety||'runbook pending')}</div></div><button data-resolve="${esc(i.incidentId)}">Resolve</button></div>`;}).join('');}
function historyRows(items){if(!items?.length)return'<div class="gov-muted">ยังไม่มี governance history</div>';return items.map(h=>`<div class="gov-row"><b>#${esc(h.snapshotId)}</b><div>${badge(h.status)}</div><div>score ${esc(h.score)} · mode ${esc(h.mode)}<br><span class="gov-muted">${esc(fmt(h.createdAt))}</span></div><span></span></div>`).join('');}
function render(root,report,history=[],incidents=[]){const b=root.querySelector('.gov-body');const t=report.telemetry||{};const active=t.activeLearning?.run;const bench=t.releaseGate?.evidence?.benchmark||report.telemetry?.benchmark?.lastRun?.summary?.sentinel;const release=t.releaseGate||{};b.innerHTML=`
<div class="gov-grid">${card('Governance status',report.status,report.phase)}${card('Score',report.score,'100 = no active signal')}${card('Mode',report.mode,report.autopilot?'autonomous actions enabled':'observe / no mutation')}${card('Open incidents',incidents.length,'deduplicated incident ledger')}${card('Release Gate',release.mergeAllowed?'MERGE READY':'BLOCKED',`score ${release.score??'-'}`)}${card('Benchmark score',bench?.score??'-',bench?`rank ${bench.rank??'-'} · passed ${bench.passed?'yes':'no'}`:'no evidence')}${card('Active Learning',active?.status||'none',active?.runId||'no active run')}</div>
<div class="gov-section"><div class="gov-actions"><button id="gov-refresh" class="gov-primary">ตรวจตอนนี้</button><button id="gov-execute">Evaluate + execute safe actions</button><button id="gov-observe">Mode: observe</button><button id="gov-auto" class="gov-danger">Mode: autopilot</button><button id="gov-off">Mode: off</button></div><div class="gov-muted" style="margin-top:8px">Autopilot อนุญาตเฉพาะ safe actions: หยุด Active Learning เมื่อเสี่ยง, trigger Release Gate benchmark/repair, run auto-review backlog และเปิด/ปิด incident อัตโนมัติ — ไม่ merge หรือ deploy เอง</div></div>
<div class="gov-section"><h3>Incident Ledger + Runbook</h3>${incidentRows(incidents)}</div>
<div class="gov-section"><h3>Governance Signals</h3>${signalRows(report.signals)}</div>
<div class="gov-section"><h3>Planned / Executed Actions</h3>${actionRows(report.actions,report.executed)}</div>
<div class="gov-section"><h3>Recommendations</h3>${(report.recommendations||[]).map(x=>`<div>• ${esc(x)}</div>`).join('')||'<div class="gov-muted">ไม่มีคำแนะนำเพิ่มเติม</div>'}</div>
<div class="gov-section"><h3>History</h3>${historyRows(history)}</div>`;
root.querySelector('#gov-refresh').onclick=()=>load(root,false);root.querySelector('#gov-execute').onclick=()=>load(root,true);root.querySelector('#gov-observe').onclick=()=>setMode(root,'observe');root.querySelector('#gov-auto').onclick=()=>setMode(root,'autopilot');root.querySelector('#gov-off').onclick=()=>setMode(root,'off');root.querySelectorAll('[data-resolve]').forEach(btn=>{btn.onclick=()=>resolveIncident(root,btn.dataset.resolve);});}
async function load(root,execute=false){const b=root.querySelector('.gov-body');b.innerHTML='<div class="gov-muted">กำลังโหลด Autonomous Governance...</div>';try{const report=execute?await api('/api/governance/evaluate',{method:'POST',body:JSON.stringify({execute:true,source:'ui-execute'})}):await api('/api/governance/status?persist=true');const [h,inc]=await Promise.all([api('/api/governance/history?limit=20').catch(()=>({history:[]})),api('/api/governance/incidents?status=open&limit=20').catch(()=>({incidents:report.incidents||[]}))]);render(root,report,h.history||[],inc.incidents||report.incidents||[]);}catch(error){b.innerHTML=`<div style="color:#ff9aad">Governance unavailable: ${esc(error.message)}</div>`;}}
async function resolveIncident(root,incidentId){try{await api(`/api/governance/incidents/${encodeURIComponent(incidentId)}/resolve`,{method:'POST',body:'{}'});notify('ปิด incident แล้ว');load(root,false);}catch(error){notify('ปิด incident ไม่สำเร็จ: '+error.message);}}
async function setMode(root,mode){try{await api('/api/governance/mode',{method:'POST',body:JSON.stringify({mode})});notify(`Governance mode: ${mode}`);load(root,false);}catch(error){notify('เปลี่ยน Governance mode ไม่สำเร็จ: '+error.message);}}
function open(){if(!allowed())return notify('ต้องเป็น Admin จึงเปิด Governance ได้');ensureStyle();let root=document.getElementById(WINDOW_ID);if(root){root.style.display='flex';load(root,false);return;}root=document.createElement('div');root.id=WINDOW_ID;root.innerHTML='<div class="gov-head"><div><div class="gov-title">🧭 Autonomous Governance</div><div class="gov-muted">Phase 13 · Incident Ledger · Runbooks · Safe Autopilot</div></div><button id="gov-close">×</button></div><div class="gov-body"></div>';document.body.appendChild(root);root.querySelector('#gov-close').onclick=()=>{root.style.display='none';};load(root,false);}
function installLauncher(){if(!allowed())return;const apps=document.getElementById('sm-apps');if(apps&&!document.getElementById('phase13-governance-launcher')){const btn=document.createElement('button');btn.id='phase13-governance-launcher';btn.className='sm-app';btn.type='button';btn.innerHTML='<span>🧭</span><b>Governance</b>';btn.onclick=open;apps.appendChild(btn);window.dispatchEvent(new CustomEvent('panthorium:apps-changed',{detail:{app:'phase13-governance'}}));}}
function boot(){installLauncher();}
window.addEventListener('panthorium:auth-changed',boot);window.addEventListener('panthorium:desktop-ready',boot);window.addEventListener('panthorium:apps-changed',boot);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.PanthoriumGovernance={open,refresh:()=>{const root=document.getElementById(WINDOW_ID);if(root)load(root,false);}};
})();
