(function(){
'use strict';
function getOS(){try{return typeof OS!=='undefined'?OS:null;}catch(_){return null;}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
async function token(){const os=getOS();if(os?.config?.accessToken)return os.config.accessToken;if(window.PanthoriumAuth?.refreshSession){const ok=await window.PanthoriumAuth.refreshSession().catch(()=>false);if(ok)return getOS()?.config?.accessToken||'';}return'';}
async function api(path,options={},retry=true){let t=await token();const headers={...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(t)headers.Authorization=`Bearer ${t}`;let res=await fetch(path,{...options,headers,credentials:'include'});if(res.status===401&&retry&&window.PanthoriumAuth?.refreshSession){const ok=await window.PanthoriumAuth.refreshSession().catch(()=>false);if(ok){t=getOS()?.config?.accessToken||'';headers.Authorization=`Bearer ${t}`;res=await fetch(path,{...options,headers,credentials:'include'});}}const data=await res.json().catch(()=>({}));if(!res.ok){const e=new Error(data.error||`HTTP ${res.status}`);e.status=res.status;e.data=data;throw e;}return data;}
function fmt(v){try{return v?new Date(v).toLocaleString('th-TH'):'-';}catch(_){return String(v||'-');}}
function badge(v){return `<span style="font-size:10px;padding:2px 7px;border:1px solid #475569;border-radius:999px">${esc(v)}</span>`;}
function integrationRow(x){return `<div style="padding:10px 0;border-bottom:1px solid #1e293b"><div><b>${esc(x.name)}</b> ${badge(x.enabled?'enabled':'disabled')}</div><div style="font-size:11px;color:#94a3b8;word-break:break-all;margin-top:4px">${esc(x.endpointUrl)}</div><div style="font-size:10px;color:#64748b;margin-top:4px">${esc(x.secretEnvKey||'no secret')} · ${esc(fmt(x.updatedAt))}</div><div style="margin-top:7px"><button data-toggle="${esc(x.integrationId)}" data-enabled="${x.enabled?'1':'0'}">${x.enabled?'Disable':'Enable'}</button> <button data-history="${esc(x.integrationId)}">History</button> <button data-delete="${esc(x.integrationId)}">Delete</button></div></div>`;}
function executionRow(x){return `<div style="padding:9px 0;border-bottom:1px solid #1e293b"><div>${badge(x.status||'-')} HTTP ${esc(x.httpStatus??'-')} · ${esc(x.durationMs??'-')} ms</div><div style="font-size:10px;color:#64748b;margin-top:4px">${esc(fmt(x.createdAt))} · ${esc(x.errorCode||'ok')}</div>${x.responsePreview?`<pre style="white-space:pre-wrap;word-break:break-word;font-size:10px;color:#cbd5e1">${esc(String(x.responsePreview).slice(0,800))}</pre>`:''}</div>`;}
async function refresh(root){const state=root.querySelector('[data-state]');state.textContent='กำลังโหลด...';try{const [list,history]=await Promise.all([api('/api/integrations'),api('/api/integrations/history?limit=40')]);root.querySelector('[data-list]').innerHTML=(list.integrations||[]).map(integrationRow).join('')||'<div style="color:#64748b">ยังไม่มี integration</div>';root.querySelector('[data-execs]').innerHTML=(history.executions||[]).map(executionRow).join('')||'<div style="color:#64748b">ยังไม่มี execution history</div>';bind(root);state.textContent=`พร้อม · ${(list.integrations||[]).length} integrations`;}catch(e){state.textContent='โหลดไม่สำเร็จ: '+e.message;}}
function bind(root){root.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api(`/api/integrations/${encodeURIComponent(b.dataset.toggle)}/enabled`,{method:'POST',body:JSON.stringify({enabled:b.dataset.enabled!=='1'})});await refresh(root);}catch(e){alert(e.message);b.disabled=false;}});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('ลบ integration นี้?'))return;b.disabled=true;try{await api(`/api/integrations/${encodeURIComponent(b.dataset.delete)}`,{method:'DELETE'});await refresh(root);}catch(e){alert(e.message);b.disabled=false;}});root.querySelectorAll('[data-history]').forEach(b=>b.onclick=async()=>{try{const h=await api(`/api/integrations/history?integrationId=${encodeURIComponent(b.dataset.history)}&limit=50`);root.querySelector('[data-execs]').innerHTML=(h.executions||[]).map(executionRow).join('')||'<div style="color:#64748b">ไม่มี history</div>';}catch(e){alert(e.message);}});}
async function create(root){const name=root.querySelector('[data-name]').value.trim();const endpointUrl=root.querySelector('[data-endpoint]').value.trim();const secretEnvKey=root.querySelector('[data-secret]').value.trim();const btn=root.querySelector('[data-create]');btn.disabled=true;try{await api('/api/integrations',{method:'POST',body:JSON.stringify({name,endpointUrl,secretEnvKey:secretEnvKey||undefined})});root.querySelector('[data-name]').value='';root.querySelector('[data-endpoint]').value='';root.querySelector('[data-secret]').value='';await refresh(root);}catch(e){alert(e.message);}finally{btn.disabled=false;}}
async function open(){if(document.getElementById('integrations-dashboard'))return;const root=document.createElement('div');root.id='integrations-dashboard';root.style.cssText='position:fixed;inset:4%;z-index:10040;background:rgba(7,11,18,.99);border:1px solid #334155;border-radius:16px;color:#e2e8f0;padding:16px;display:flex;flex-direction:column;box-shadow:0 24px 80px #000;font-family:system-ui;overflow:hidden';root.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px"><div><h2 style="margin:0">🔌 Integrations & External Actions</h2><div data-state style="font-size:11px;color:#7f93aa">กำลังโหลด...</div></div><div><button data-refresh>Refresh</button> <button data-close>✕</button></div></div><div style="display:grid;grid-template-columns:minmax(300px,.9fr) minmax(320px,1.1fr);gap:12px;overflow:hidden;flex:1;margin-top:12px"><div style="display:flex;flex-direction:column;overflow:hidden"><section style="border:1px solid #263548;border-radius:12px;background:#0b1220;padding:12px"><b>Create Integration</b><input data-name placeholder="Name" style="width:100%;box-sizing:border-box;margin-top:8px;background:#0f172a;color:#e2e8f0;border:1px solid #334155;border-radius:8px;padding:8px"><input data-endpoint placeholder="https://allowed-host/path" style="width:100%;box-sizing:border-box;margin-top:7px;background:#0f172a;color:#e2e8f0;border:1px solid #334155;border-radius:8px;padding:8px"><input data-secret placeholder="PANTHORIUM_INTEGRATION_SECRET_... (optional)" style="width:100%;box-sizing:border-box;margin-top:7px;background:#0f172a;color:#e2e8f0;border:1px solid #334155;border-radius:8px;padding:8px"><div style="font-size:10px;color:#94a3b8;margin-top:7px">Secret values stay in server environment variables only.</div><button data-create style="margin-top:9px">Create</button></section><section style="border:1px solid #263548;border-radius:12px;background:#0b1220;padding:12px;margin-top:12px;overflow:auto;flex:1"><b>Integrations</b><div data-list style="margin-top:6px"></div></section></div><section style="border:1px solid #263548;border-radius:12px;background:#0b1220;padding:12px;overflow:auto"><b>Execution History / Observability</b><div data-execs style="margin-top:6px"></div></section></div>`;document.body.appendChild(root);root.querySelector('[data-close]').onclick=()=>root.remove();root.querySelector('[data-refresh]').onclick=()=>refresh(root);root.querySelector('[data-create]').onclick=()=>create(root);refresh(root);}
function install(){const menu=document.querySelector('.start-menu, #start-menu');if(!menu||document.getElementById('phase9-integrations-launcher'))return !!menu;const b=document.createElement('button');b.id='phase9-integrations-launcher';b.textContent='🔌 Integrations';b.style.cssText='display:block;width:100%;padding:10px;text-align:left';b.onclick=open;menu.appendChild(b);return true;}
window.PanthoriumIntegrations={open,refresh};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();let n=0;const timer=setInterval(()=>{n++;if(install()||n>30)clearInterval(timer);},500);
})();
