(function(){
'use strict';
function os(){try{return typeof OS!=='undefined'?OS:null;}catch(_){return null;}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function allowed(){return window.PanthoriumAuth?.hasPermission?.('settings')===true;}
function notify(message){if(typeof toast==='function')toast(message);else console.log('[Release Gate]',message);}
async function refreshToken(){const s=os();if(s?.config?.accessToken)return s.config.accessToken;if(window.PanthoriumAuth?.refreshSession){const ok=await window.PanthoriumAuth.refreshSession().catch(()=>false);if(ok)return os()?.config?.accessToken||'';}return'';}
async function api(path,options={},retry=true){let token=os()?.config?.accessToken||'';if(!token)token=await refreshToken();const headers={...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers,credentials:'include'});const data=await response.json().catch(()=>({}));if(response.status===401&&retry&&window.PanthoriumAuth?.refreshSession){const ok=await window.PanthoriumAuth.refreshSession().catch(()=>false);if(ok)return api(path,options,false);}if(!response.ok){const error=new Error(data.error||`HTTP ${response.status}`);error.data=data;throw error;}return data;}
function ensureStyle(){if(document.getElementById('sentinel-release-gate-style'))return;const s=document.createElement('style');s.id='sentinel-release-gate-style';s.textContent=`
#st-release-gate{margin:12px 0;padding:13px;border:1px solid #34506a;border-radius:14px;background:linear-gradient(135deg,rgba(12,27,45,.96),rgba(5,16,28,.92));box-shadow:0 0 0 1px rgba(134,255,221,.05) inset}
#st-release-gate .rg-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}#st-release-gate .rg-title{font-weight:900;color:#e9fbff}#st-release-gate .rg-score{font-size:26px;font-weight:900;color:#86ffdd}#st-release-gate .rg-badge{font-weight:900;padding:5px 9px;border-radius:999px;border:1px solid #31506a}#st-release-gate .rg-pass{color:#8affc8;border-color:#1f8f69;background:#09251f}#st-release-gate .rg-block{color:#ff9aad;border-color:#7f2c3e;background:#25101a}#st-release-gate .rg-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:8px;margin-top:10px}#st-release-gate .rg-check{border:1px solid #25405a;background:#071421;border-radius:10px;padding:9px}#st-release-gate .rg-check b{display:block;margin-bottom:4px}#st-release-gate .rg-muted{font-size:11px;color:#9db6ca}#st-release-gate .rg-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}#st-release-gate button{border:1px solid #31506a;background:#0d1d2d;color:#dffcff;border-radius:9px;padding:8px 11px;cursor:pointer}#st-release-gate button:hover{border-color:#00d9b7}#st-release-gate button:disabled{opacity:.6;cursor:not-allowed}.rg-primary{border-color:#00d9b7!important;background:#073c3a!important}.rg-warn{border-color:#806a29!important;background:#2a2210!important;color:#fff1c0!important}.rg-job{margin-top:8px;padding:8px;border:1px solid #25405a;border-radius:10px;background:#071421}.rg-job.running{border-color:#806a29}.rg-job.completed{border-color:#1f8f69}.rg-job.failed{border-color:#7f2c3e}
`;document.head.appendChild(s);}
function icon(pass){return pass?'<span style="color:#8affc8">✓ ผ่าน</span>':'<span style="color:#ff9aad">✕ ติด blocker</span>';}
function host(){return document.getElementById('st-acceptance')||document.getElementById('st-summary')||document.querySelector('#sentinel-training-lab [data-pane="dashboard"]');}
function hasBenchmarkBlocker(report){return (report.blockers||[]).some(b=>b.id==='benchmark_evidence');}
function jobLine(job){if(!job)return'';const status=job.status||'-';const sentinel=job.result?.sentinel;const detail=job.error?`error: ${job.error}`:sentinel?`Sentinel score ${sentinel.score} · rank ${sentinel.rank} · ${job.result?.mergeReadyIfRechecked?'ผ่านขั้นต่ำ':'ยังต่ำกว่าขั้นต่ำ'}`:`cases ${job.cases||0} · providers ${(job.providers||[]).join(', ')||'-'}`;return `<div class="rg-job ${esc(status)}"><b>Benchmark job: ${esc(status)}</b><div class="rg-muted">${esc(detail)}</div></div>`;}
function render(report){const p=document.getElementById('st-release-gate');if(!p)return;const checks=Array.isArray(report.checks)?report.checks:[];const benchmarkBlocked=hasBenchmarkBlocker(report);const job=report.releaseBenchmarkJob;const jobRunning=job?.status==='running';p.innerHTML=`<div class="rg-head"><div><div class="rg-title">🚦 Production Release Gate</div><div class="rg-muted">ตรวจหลักฐานก่อน merge Production: Dashboard · Shadow Gate · Recovery · Active Learning · Benchmark</div></div><div style="display:flex;align-items:center;gap:10px"><div class="rg-score">${esc(report.score||0)}%</div><div class="rg-badge ${report.mergeAllowed?'rg-pass':'rg-block'}">${report.mergeAllowed?'MERGE READY':'BLOCKED'}</div></div></div><div class="rg-grid">${checks.map(c=>`<div class="rg-check"><b>${esc(c.label)}</b><div>${icon(c.pass)}</div><div class="rg-muted">${esc(c.reason||'evidence OK')}</div></div>`).join('')}</div>${report.blockers?.length?`<div class="rg-muted" style="margin-top:8px;color:#ff9aad">Blockers: ${esc(report.blockers.map(b=>b.label).join(', '))}</div>`:''}${report.warnings?.length?`<div class="rg-muted" style="margin-top:6px;color:#ffd77a">Warnings: ${esc(report.warnings.map(w=>w.warning).join(' · '))}</div>`:''}${benchmarkBlocked?`<div class="rg-muted" style="margin-top:8px;color:#ffd77a">Benchmark blocker ยังเหลืออยู่: กด “รัน Benchmark Release Gate” ระบบจะสั่ง backend ให้รันแบบ background แล้วติดตามผลอัตโนมัติ</div>`:''}${jobLine(job)}<div class="rg-actions"><button id="rg-check">ตรวจ Release Gate ตอนนี้</button><button id="rg-benchmark" class="${benchmarkBlocked?'rg-primary':'rg-warn'}" ${jobRunning?'disabled':''}>${jobRunning?'⚔ กำลังรัน Benchmark...':'⚔ รัน Benchmark Release Gate'}</button><button id="rg-copy">Copy evidence JSON</button></div>`;const check=document.getElementById('rg-check'),copy=document.getElementById('rg-copy'),bench=document.getElementById('rg-benchmark');if(check)check.onclick=refresh;if(copy)copy.onclick=()=>navigator.clipboard?.writeText(JSON.stringify(report,null,2)).then(()=>notify('คัดลอก release gate evidence แล้ว')).catch(()=>notify('คัดลอกไม่สำเร็จ'));if(bench)bench.onclick=startBenchmarkEvidence;if(jobRunning)watchBenchmarkJob(3000);}
async function refresh(){const p=document.getElementById('st-release-gate');if(!p||!allowed())return;try{p.innerHTML='<div class="rg-muted">กำลังตรวจ Production Release Gate...</div>';render(await api('/api/training/release-gate/status?record=true'));}catch(error){p.innerHTML=`<div style="color:#ff9aad">Release Gate unavailable: ${esc(error.message)}</div>`;}}
async function startBenchmarkEvidence(){const p=document.getElementById('st-release-gate');const btn=document.getElementById('rg-benchmark');if(btn)btn.disabled=true;try{if(p)p.insertAdjacentHTML('beforeend','<div class="rg-muted" style="margin-top:8px;color:#ffd77a">ส่งงาน Benchmark ไป backend แล้ว ระบบจะติดตามผลอัตโนมัติ ไม่ต้องรอ request ค้างหน้า browser...</div>');const accepted=await api('/api/training/release-gate/benchmark/start',{method:'POST',body:'{}'});notify(accepted.alreadyRunning?'Benchmark กำลังรันอยู่แล้ว':'เริ่ม Benchmark Release Gate แล้ว');await watchBenchmarkJob(1500);}catch(error){notify('เริ่ม Benchmark Release Gate ไม่สำเร็จ: '+error.message);if(p)p.insertAdjacentHTML('beforeend',`<div class="rg-muted" style="margin-top:8px;color:#ff9aad">Benchmark error: ${esc(error.message)}</div>`);if(btn)btn.disabled=false;}}
let watchTimer=null;
async function watchBenchmarkJob(delay){if(watchTimer)clearTimeout(watchTimer);watchTimer=setTimeout(async()=>{try{const status=await api('/api/training/release-gate/benchmark/status');if(status.job?.status==='running'){const p=document.getElementById('st-release-gate');if(p&&!p.querySelector('.rg-job.running'))await refresh();return watchBenchmarkJob(3000);}await refresh();if(status.job?.status==='completed'){const score=status.job.result?.sentinel?.score;notify(`Benchmark เสร็จแล้ว: Sentinel score ${score??'-'}`);if(window.PanthoriumTraining?.refresh)window.PanthoriumTraining.refresh();}else if(status.job?.status==='failed'){notify('Benchmark ล้มเหลว: '+(status.job.error||'unknown_error'));}}catch(error){notify('ติดตาม Benchmark ไม่สำเร็จ: '+error.message);}},Math.max(500,Number(delay)||3000));}
function install(){if(!allowed())return;const h=host();if(!h||document.getElementById('st-release-gate'))return;ensureStyle();const p=document.createElement('div');p.id='st-release-gate';p.innerHTML='<div class="rg-muted">กำลังโหลด Production Release Gate...</div>';h.insertAdjacentElement('afterend',p);refresh();}
const observer=new MutationObserver(()=>{if(document.getElementById('sentinel-training-lab'))install();});
function boot(){try{observer.observe(document.body,{childList:true,subtree:true});}catch(_){}install();}
window.addEventListener('panthorium:auth-changed',()=>setTimeout(install,0));
window.addEventListener('panthorium:training-opened',()=>setTimeout(install,0));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.PanthoriumReleaseGate={refresh,status:()=>api('/api/training/release-gate/status'),startBenchmarkEvidence};
})();
