/** Panthorium OS Backend */
require("dotenv").config();
const path = require("path"); const fs = require("fs"); const express = require("express"); const cors = require("cors"); const helmet = require("helmet"); const cookieParser = require("cookie-parser");
const config = require("./config"); const { createAuthRepository } = require("./repositories/authRepository");
const { AuditService } = require("./services/auditService"); const { AuthService } = require("./services/authService"); const { SecurityResponseService } = require("./services/securityResponseService"); const { ConversationRepository } = require("./services/conversationRepository"); const { AiOperationsService } = require("./services/aiOperationsService"); const { SentinelCore } = require("./services/sentinelCore"); const { ToolRegistry } = require("./services/toolRegistry"); const { AgentService } = require("./services/agentService"); const { AgentPlannerService } = require("./services/agentPlannerService"); const { AgentWorkflowService } = require("./services/agentWorkflowService"); const { AgentRunRepository } = require("./services/agentRunRepository"); const { AgentPendingRepository } = require("./services/agentPendingRepository"); const { AgentJobRepository } = require("./services/agentJobRepository"); const { AgentSchedulerService } = require("./services/agentSchedulerService"); const { AgentAutomationRepository } = require("./services/agentAutomationRepository"); const { AgentAutomationService } = require("./services/agentAutomationService"); const { AgentPolicyService } = require("./services/agentPolicyService");
const { createApiRouter } = require("./routes/api"); const { createAuthRouter } = require("./routes/auth"); const { createSecurityRouter } = require("./routes/security"); const { requestContext } = require("./middleware/requestContext");
const app = express(); if (config.trustProxy) app.set("trust proxy", 1);
const authRepository = createAuthRepository(config); const audit = new AuditService({ file: config.auditFile, databaseUrl: config.databaseUrl, databaseSslMode: config.databaseSslMode }); const securityResponse = new SecurityResponseService({ audit, databaseUrl: config.databaseUrl, databaseSslMode: config.databaseSslMode }); const authService = new AuthService({ repository: authRepository, config, audit }); const conversations = new ConversationRepository({ databaseUrl: config.databaseUrl, databaseSslMode: config.databaseSslMode }); const aiOperations = new AiOperationsService({ audit, conversations }); const agentRuns = new AgentRunRepository({ databaseUrl: config.databaseUrl, databaseSslMode: config.databaseSslMode }); const agentPending = new AgentPendingRepository({ databaseUrl: config.databaseUrl, databaseSslMode: config.databaseSslMode }); const agentJobs = new AgentJobRepository({ databaseUrl: config.databaseUrl, databaseSslMode: config.databaseSslMode }); const agentAutomationRepository = new AgentAutomationRepository({ databaseUrl: config.databaseUrl, databaseSslMode: config.databaseSslMode }); const sentinelCore = new SentinelCore({ conversations, audit }); const toolRegistry = new ToolRegistry({ sentinelCore, conversations, securityResponse, aiOperations }); const agentPolicy = new AgentPolicyService(); const agentService = new AgentService({ tools: toolRegistry, audit, policy: agentPolicy }); const agentPlanner = new AgentPlannerService({ agentService, gateway: sentinelCore.gateway, audit }); const agentWorkflow = new AgentWorkflowService({ agentService, gateway: sentinelCore.gateway, audit, runs: agentRuns, pendingStore: agentPending }); const agentAutomation = new AgentAutomationService({ repository: agentAutomationRepository, jobs: agentJobs, audit }); const agentScheduler = new AgentSchedulerService({ jobs: agentJobs, workflow: agentWorkflow, runs: agentRuns, audit, authService, automation: agentAutomation });
app.disable("x-powered-by");
app.use(helmet({ contentSecurityPolicy: { directives: { defaultSrc: ["'self'"], scriptSrc: ["'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com"], styleSrc: ["'self'", "'unsafe-inline'"], imgSrc: ["'self'", "data:", "blob:"], mediaSrc: ["'self'", "blob:"], connectSrc: ["'self'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com", ...config.allowedOrigins], workerSrc: ["'self'", "blob:"], objectSrc: ["'none'"], frameAncestors: ["'none'"] } }, crossOriginEmbedderPolicy: false }));
app.use(cors({ origin(origin, callback) { if (!origin || config.allowedOrigins.includes(origin)) return callback(null, true); return callback(new Error("CORS origin denied")); }, credentials: true })); app.use(express.json({ limit: "256kb", type: "application/json" })); app.use(cookieParser()); app.use(requestContext(audit));
app.use("/api/auth", createAuthRouter(authService, config, securityResponse)); app.use("/api/security", createSecurityRouter(authService, authRepository, audit, securityResponse)); app.use("/api", createApiRouter(sentinelCore, authService, audit, aiOperations, agentService, agentPlanner, agentWorkflow, agentRuns, agentScheduler, agentAutomation));
const frontendCandidates = [path.join(__dirname, ".."), __dirname]; const frontendRoot = frontendCandidates.find((dir) => fs.existsSync(path.join(dir, "sentinel.html"))) || __dirname;
app.get("/sw.js", (req, res, next) => { try { res.set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate"); res.set("Service-Worker-Allowed", "/"); res.type("application/javascript").sendFile(path.join(frontendRoot, "sw.js")); } catch (error) { next(error); } });
const shellScripts = ["boot-recovery.js","branding.js","phase2-auth.js","user-manager.js","security-dashboard.js","ui-layout.js","ai-dashboard.js","ai-stream-client.js","agent-ui.js"];
for (const script of shellScripts) app.get(`/${script}`, (req, res, next) => { try { res.set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate"); res.sendFile(path.join(frontendRoot, script)); } catch (error) { next(error); } });
function renderShell() { let html = fs.readFileSync(path.join(frontendRoot, "sentinel.html"), "utf8"); const version = "phase6-automation-triggers-v1"; for (const script of shellScripts) if (!html.includes(`/${script}`)) html = html.replace(/<\/body>/i, `  <script src="/${script}?v=${version}"></script>\n</body>`); return html; }
function serveShell(req, res, next) { try { res.set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate"); res.set("Surrogate-Control", "no-store"); res.type("html").send(renderShell()); } catch (error) { next(error); } }
app.get("/", serveShell); app.get("/sentinel.html", serveShell); app.use(express.static(frontendRoot, { index: false, etag: true, maxAge: config.isProduction ? "1h" : 0 })); app.use((req, res) => res.status(404).json({ ok: false, error: "not_found" }));
app.use((err, req, res, next) => { console.error("[HTTP]", err.message); if (err.message === "CORS origin denied") return res.status(403).json({ ok: false, error: "cors_denied" }); res.status(500).json({ ok: false, error: "internal_error" }); });
async function start() { await audit.init(); await securityResponse.init(); await authService.init(); await conversations.init(); await agentRuns.init(); await agentPending.init(); await agentScheduler.init(); const server = app.listen(config.port, config.host, () => { console.log("========================================"); console.log("  Panthorium OS Backend · Phase 6 Agent Automation"); console.log(`  Conversation persistence: ${config.databaseUrl ? "PostgreSQL" : "memory"}`); console.log(`  Agent run history: ${config.databaseUrl ? "PostgreSQL" : "memory"}`); console.log(`  Pending confirmations: ${config.databaseUrl ? "PostgreSQL" : "memory"}`); console.log(`  Scheduled + recurring jobs: ${config.databaseUrl ? "PostgreSQL" : "memory"}`); console.log(`  Agent tools: ${toolRegistry.catalog().length}`); console.log("  Persistent workflows + schedules + event triggers online"); console.log(`  http://localhost:${config.port}`); console.log("========================================"); }); agentScheduler.start(); return server; }
if (require.main === module) start().catch((error) => { console.error("[BOOT]", error); process.exit(1); }); module.exports = { app, sentinelCore, authService, securityResponse, conversations, aiOperations, toolRegistry, agentPolicy, agentService, agentPlanner, agentWorkflow, agentRuns, agentPending, agentJobs, agentAutomationRepository, agentAutomation, agentScheduler, start };