(function(){
'use strict';
function os(){try{return typeof OS!=='undefined'?OS:null;}catch(_){return null;}}
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));}
function allowed(){return window.PanthoriumAuth?.hasPermission?.('settings')===true;}
async function refreshToken(){const system=os();if(system?.config?.accessToken)return system.config.accessToken;if(window.PanthoriumAuth?.refreshSession){const ok=await window.PanthoriumAuth.refreshSession().catch(()=>false);if(ok)return system?.config?.accessToken||'';}return'';}
async function api(path,options={},retry=true){const system=os();let token=system?.config?.accessToken||'';if(!token)token=await refreshToken();const headers={...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers,credentials:'include'});const data=await response.json().catch(()=>({}));if(response.status===401&&retry&&window.PanthoriumAuth?.refreshSession){const ok=await window.PanthoriumAuth.refreshSession().catch(()=>false);if(ok)return api(path,options,false);}if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;}
function notify(message){if(typeof toast==='function')toast(message);else alert(message);}
function field(id,label,placeholder,rows=3){return `<label style="display:block;margin:8px 0 4px;color:#9fb1c7;font-size:12px">${esc(label)}</label><textarea id="${id}" rows="${rows}" placeholder="${esc(placeholder)}" style="width:100%;box-sizing:border-box;padding:10px;border-radius:9px;border:1px solid #334155;background:#07101d;color:#e2e8f0;resize:vertical"></textarea>`;}
function open(){
 if(!allowed()){notify('เมนูนี้สำหรับผู้ดูแลระบบ');return;}if(document.getElementById('sentinel-training-lab'))return;
 const wrap=document.createElement('div');wrap.id='sentinel-training-lab';wrap.style.cssText='position:fixed;inset:4%;z-index:9999;background:rgba(7,12,21,.99);border:1px solid #334155;border-radius:16px;color:#e2e8f0;padding:20px;overflow:auto;font-family:system-ui;box-shadow:0 24px 90px #000';
 wrap.innerHTML=`<button id="training-close" style="float:right">✕</button><h2>🎓 Sentinel Training Lab</h2><p style="color:#93a4b8">เทรน ตรวจ ให้คะแนน และอนุมัติความรู้อัตโนมัติ โดย Sentinel นำไปใช้เฉพาะรายการที่ผ่านเกณฑ์</p><div id="training-stats" style="margin:12px 0">กำลังโหลด...</div><div id="training-auto" style="margin:10px 0;padding:10px;border:1px solid #14532d;border-radius:10px;background:#052e16;color:#86efac">กำลังตรวจสถานะอัตโนมัติ...</div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px"><section style="padding:14px;border:1px solid #263548;border-radius:12px"><h3>AI ครู</h3>${field('teacher-prompt','โจทย์ฝึก','ใส่คำถามหรือสถานการณ์ที่ Sentinel ควรตอบให้เก่งขึ้น',5)}<label style="display:block;margin:8px 0 4px;color:#9fb1c7;font-size:12px">แท็ก (คั่นด้วย comma)</label><input id="teacher-tags" placeholder="panthorium, support" style="width:100%;box-sizing:border-box;padding:10px;border-radius:9px;border:1px solid #334155;background:#07101d;color:#e2e8f0"><button id="teacher-draft" style="margin-top:10px">สร้างและประเมินคำตอบอัตโนมัติ</button><div style="font-size:11px;color:#fbbf24;margin-top:8px">อาจใช้โควตาหรือเครดิตของ provider ที่เปิดอยู่</div></section><section style="padding:14px;border:1px solid #263548;border-radius:12px"><h3>เพิ่มตัวอย่างด้วยตนเอง</h3>${field('manual-prompt','คำถาม','คำถามตัวอย่าง',3)}${field('manual-answer','คำตอบที่ถูกต้อง','คำตอบที่ต้องการให้ Sentinel ใช้เป็นแนวทาง',5)}<button id="manual-add" style="margin-top:10px">เพิ่มและประเมินอัตโนมัติ</button></section></div><div style="display:flex;gap:8px;align-items:center;margin:18px 0 8px;flex-wrap:wrap"><h3 style="margin:0">ประวัติการฝึก</h3><button id="training-refresh">รีเฟรช</button><button id="training-auto-run">ตรวจคิวตอนนี้</button><button id="training-export">ส่งออก JSONL</button></div><div id="training-list">กำลังโหลด...</div>`;
 document.body.appendChild(wrap);document.getElementById('training-close').onclick=()=>wrap.remove();document.getElementById('training-refresh').onclick=refresh;document.getElementById('training-auto-run').onclick=runAuto;document.getElementById('training-export').onclick=exportData;document.getElementById('teacher-draft').onclick=draft;document.getElementById('manual-add').onclick=addManual;refresh();
}
function tags(id){return(document.getElementById(id)?.value||'').split(',').map(value=>value.trim()).filter(Boolean);}
async function draft(){const button=document.getElementById('teacher-draft');const prompt=document.getElementById('teacher-prompt')?.value||'';if(!prompt.trim()){notify('กรุณาใส่โจทย์ฝึก');return;}button.disabled=true;button.textContent='AI กำลังสร้าง ตรวจ และให้คะแนน...';try{const result=await api('/api/training/teachers/draft',{method:'POST',body:JSON.stringify({prompt,tags:tags('teacher-tags')})});notify(`สร้างและประเมินอัตโนมัติ ${result.candidates?.length||0} รายการ`);document.getElementById('teacher-prompt').value='';await refresh();}catch(error){notify(error.message==='no_teacher_provider'?'ยังไม่ได้ตั้งค่า AI Provider/API key':'สร้างคำตอบไม่สำเร็จ: '+error.message);}finally{button.disabled=false;button.textContent='สร้างและประเมินคำตอบอัตโนมัติ';}}
async function addManual(){const prompt=document.getElementById('manual-prompt')?.value||'';const answer=document.getElementById('manual-answer')?.value||'';try{const result=await api('/api/training/examples',{method:'POST',body:JSON.stringify({prompt,answer,source:'human'})});document.getElementById('manual-prompt').value='';document.getElementById('manual-answer').value='';notify(result.example?.status==='approved'?'ตรวจและอนุมัติอัตโนมัติแล้ว':result.example?.status==='rejected'?'ตรวจแล้วแต่คะแนนไม่ผ่าน':'เพิ่มเข้าคิวตรวจอัตโนมัติแล้ว');await refresh();}catch(error){notify('เพิ่มไม่สำเร็จ: '+error.message);}}
async function runAuto(){const button=document.getElementById('training-auto-run');button.disabled=true;button.textContent='กำลังตรวจ...';try{const result=await api('/api/training/auto/run',{method:'POST',body:JSON.stringify({limit:25})});notify(`ตรวจ ${result.processed||0} · ผ่าน ${result.approved||0} · ไม่ผ่าน ${result.rejected||0}`);await refresh();}catch(error){notify('ตรวจอัตโนมัติไม่สำเร็จ: '+error.message);}finally{button.disabled=false;button.textContent='ตรวจคิวตอนนี้';}}
async function review(id,status){try{await api(`/api/training/examples/${encodeURIComponent(id)}/${status}`,{method:'POST',body:'{}'});notify(status==='approve'?'อนุมัติแล้ว Sentinel พร้อมใช้ตัวอย่างนี้':'ปฏิเสธแล้ว');await refresh();}catch(error){notify('ดำเนินการไม่สำเร็จ: '+error.message);}}
async function refresh(){
 const list=document.getElementById('training-list');if(!list)return;
 try{
  const data=await api('/api/training/examples?limit=100');const stats=data.stats||{};const automatic=data.automatic||{};
  document.getElementById('training-stats').innerHTML=`ทั้งหมด <b>${esc(stats.total||0)}</b> · รอตรวจ <b>${esc(stats.pending||0)}</b> · อนุมัติ <b>${esc(stats.approved||0)}</b> · ปฏิเสธ <b>${esc(stats.rejected||0)}</b> · อนุมัติอัตโนมัติ <b>${esc(stats.autoApproved||0)}</b> · คะแนนเฉลี่ย <b>${esc(stats.averageScore||0)}</b>`;
  document.getElementById('training-auto').innerHTML=automatic.enabled?`● ระบบอัตโนมัติทำงาน · เก็บบทสนทนา ${automatic.capture?'เปิด':'ปิด'} · เกณฑ์อนุมัติ <b>${esc(automatic.scoreThreshold)}</b>/100 · ผู้ตรวจ ${esc((automatic.providers||[]).join(', ')||'ยังไม่ตั้งค่า')}`:'○ ระบบอัตโนมัติปิดอยู่';
  list.innerHTML=data.examples?.length?data.examples.map(item=>{const status=item.status==='approved'?'✓ อนุมัติแล้ว':item.status==='rejected'?'✕ ไม่ผ่าน':'⏳ รอตรวจ';const color=item.status==='approved'?'#86efac':item.status==='rejected'?'#fca5a5':'#fde68a';const controls=item.status==='pending'?`<div style="display:flex;gap:8px;margin-top:10px"><button data-training-approve="${esc(item.exampleId)}">✓ อนุมัติ</button><button data-training-reject="${esc(item.exampleId)}">✕ ปฏิเสธ</button></div>`:'';return `<article style="padding:12px;border:1px solid #263548;border-radius:10px;margin-bottom:9px;background:#0b1220"><div style="font-size:11px;color:#7dd3fc">${esc(item.source||'human')} ${item.model?'· '+esc(item.model):''}</div><div style="font-size:12px;color:${color};margin-top:5px">${status}${item.qualityScore==null?'':' · คะแนน '+esc(item.qualityScore)+'/100'}${item.autoApproved?' · อัตโนมัติ':''}</div><div style="font-weight:700;margin:6px 0">${esc(item.prompt)}</div><div style="white-space:pre-wrap;color:#cbd5e1">${esc(item.answer)}</div>${controls}</article>`;}).join(''):'<div style="color:#94a3b8">ยังไม่มีประวัติการฝึก</div>';
  list.querySelectorAll('[data-training-approve]').forEach(button=>button.onclick=()=>review(button.dataset.trainingApprove,'approve'));list.querySelectorAll('[data-training-reject]').forEach(button=>button.onclick=()=>review(button.dataset.trainingReject,'reject'));
 }catch(error){list.textContent='โหลดข้อมูลไม่สำเร็จ: '+error.message;}
}
async function exportData(){let token=os()?.config?.accessToken||await refreshToken();const response=await fetch('/api/training/export.jsonl',{headers:{Authorization:`Bearer ${token}`}});if(!response.ok){notify('ส่งออกไม่สำเร็จ');return;}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='sentinel-training.jsonl';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function install(){const menu=document.getElementById('sm-apps')||document.querySelector('.start-menu, #start-menu');if(!menu)return;let button=document.getElementById('sentinel-training-launcher');if(!button){button=document.createElement('button');button.id='sentinel-training-launcher';button.className='sm-app';button.innerHTML='<div class="ico">🎓</div><span>Training Lab</span>';button.style.cssText='border:0;background:transparent;color:inherit;font:inherit';button.onclick=()=>{open();try{closeStartMenu();}catch(_){}};menu.appendChild(button);}button.style.display=allowed()?'':'none';}
window.PanthoriumTraining={open,refresh};window.addEventListener('panthorium:auth-changed',install);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setInterval(install,1500);
})();
