(function(){
'use strict';

const KEYS={enabled:'pt_voice_enabled',auto:'pt_voice_auto_speak',voice:'pt_voice_uri',rate:'pt_voice_rate',volume:'pt_voice_volume'};
const MAX_SPEECH_CHARS=1800;
const THAI_LOCALE='th-TH';
if(typeof window==='undefined')return;

const state={
  supported:'speechSynthesis'in window&&'SpeechSynthesisUtterance'in window,
  recognitionSupported:!!(window.SpeechRecognition||window.webkitSpeechRecognition),
  enabled:localStorage.getItem(KEYS.enabled)!=='0',
  autoSpeak:localStorage.getItem(KEYS.auto)!=='0',
  speaking:false,paused:false,activeProfile:null,activeVoice:null,voices:[],lastText:'',lastAt:0,unlocked:false
};

const PROFILE={
  'sentinel-core':{id:'sentinel-core',label:'Sentinel Core',actor:'core',lang:THAI_LOCALE,rate:.92,pitch:.72,volume:1},
  sentinel:{id:'sentinel',label:'Sentinel',actor:'sentinel',lang:THAI_LOCALE,rate:.98,pitch:1.02,volume:1}
};

function num(value,fallback,min,max){const n=Number(value);if(!Number.isFinite(n))return fallback;return Math.min(max,Math.max(min,n));}
function isAdminPath(){return /^\/admin(?:\/|\.html)?$/i.test(location.pathname);}
function profileFor(options={}){if(options.profile&&PROFILE[options.profile])return options.profile;const provider=String(options.provider||'');if(/core|sentinel core|release gate|governance|dual ai/i.test(provider))return 'sentinel-core';return isAdminPath()?'sentinel-core':'sentinel';}
function toast(message){try{if(typeof window.toast==='function')window.toast(message);else console.info('[Thai Voice]',message);}catch(_){console.info('[Thai Voice]',message);}}
function emit(type,detail={}){try{window.dispatchEvent(new CustomEvent(`panthorium:voice-${type}`,{detail:{...detail,enabled:state.enabled,autoSpeak:state.autoSpeak,speaking:state.speaking,profile:state.activeProfile,voice:state.activeVoice?.name||null,lang:state.activeVoice?.lang||THAI_LOCALE}}));}catch(_){}}
function stripHtml(text){const div=document.createElement('div');div.innerHTML=String(text||'');return div.textContent||div.innerText||'';}
function cleanText(input){let text=stripHtml(input);text=text.replace(/```[\s\S]*?```/g,' ').replace(/`([^`]+)`/g,'$1').replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/https?:\/\/\S+/g,' ลิงก์ ').replace(/[•*_#>~|]/g,' ').replace(/\s+/g,' ').trim();if(text.length>MAX_SPEECH_CHARS)text=text.slice(0,MAX_SPEECH_CHARS)+' ...';return text;}
function thaiVoiceAvailable(){return state.voices.some(v=>/^th(?:-|$)/i.test(v.lang||'')||/thai|ไทย|th-th/i.test(`${v.name||''} ${v.lang||''}`));}
function selectVoice(){if(!state.supported)return null;const voices=state.voices.length?state.voices:(window.speechSynthesis.getVoices()||[]);const saved=localStorage.getItem(KEYS.voice)||'';return voices.find(v=>v.voiceURI===saved||v.name===saved)||voices.find(v=>/^th(?:-|$)/i.test(v.lang||''))||voices.find(v=>/thai|ไทย|th-th/i.test(`${v.name} ${v.lang}`))||voices.find(v=>/th/i.test(v.lang||''))||voices.find(v=>v.default)||voices[0]||null;}
function loadVoices(render=true){if(!state.supported)return [];const voices=window.speechSynthesis.getVoices()||[];state.voices=voices.slice().sort((a,b)=>String(a.lang||'').localeCompare(String(b.lang||''))||String(a.name||'').localeCompare(String(b.name||'')));state.activeVoice=selectVoice();if(render)renderPanel();return state.voices;}
function saveEnabled(value){state.enabled=!!value;localStorage.setItem(KEYS.enabled,state.enabled?'1':'0');syncTaskbar();renderPanel();emit('enabled',{value:state.enabled});}
function saveAuto(value){state.autoSpeak=!!value;localStorage.setItem(KEYS.auto,state.autoSpeak?'1':'0');renderPanel();emit('auto',{value:state.autoSpeak});}
function speak(text,options={}){
  if(!state.supported){toast('เบราว์เซอร์นี้ยังไม่รองรับ Text-to-Speech');emit('error',{error:'speech_synthesis_not_supported'});return false;}
  const spoken=cleanText(text);if(!spoken)return false;const now=Date.now();
  if(!options.force&&state.lastText===spoken&&now-state.lastAt<2500)return false;
  if(!state.enabled&&!options.force)return false;
  const profileId=profileFor(options);const profile=PROFILE[profileId]||PROFILE.sentinel;const u=new SpeechSynthesisUtterance(spoken);
  loadVoices(false);state.activeVoice=selectVoice();if(state.activeVoice)u.voice=state.activeVoice;
  u.lang=THAI_LOCALE;u.rate=num(localStorage.getItem(KEYS.rate),profile.rate,.55,1.35);u.pitch=options.pitch!=null?num(options.pitch,profile.pitch,.1,2):profile.pitch;u.volume=num(localStorage.getItem(KEYS.volume),profile.volume,0,1);
  state.lastText=spoken;state.lastAt=now;state.activeProfile=profileId;window.speechSynthesis.cancel();
  u.onstart=()=>{state.speaking=true;state.paused=false;syncTaskbar();renderPanel();emit('start',{text:spoken,actor:profile.actor,profile:profileId});};
  u.onboundary=(event)=>emit('boundary',{charIndex:event.charIndex||0,actor:profile.actor,profile:profileId});
  const finish=()=>{state.speaking=false;state.paused=false;syncTaskbar();renderPanel();emit('end',{actor:profile.actor,profile:profileId});};
  u.onend=finish;u.onerror=(event)=>{state.speaking=false;state.paused=false;syncTaskbar();renderPanel();emit('error',{error:event.error||'speech_error',actor:profile.actor,profile:profileId});};
  window.speechSynthesis.speak(u);syncTaskbar();renderPanel();return true;
}
function speakSentinel(text,options={}){return speak(text,{...options,profile:'sentinel'});}
function speakCore(text,options={}){return speak(text,{...options,profile:'sentinel-core'});}
function stop(){if(state.supported)window.speechSynthesis.cancel();state.speaking=false;state.paused=false;syncTaskbar();renderPanel();emit('stop',{});}
function pause(){if(state.supported&&state.speaking){window.speechSynthesis.pause();state.paused=true;syncTaskbar();renderPanel();emit('pause',{});}}
function resume(){if(state.supported&&state.paused){window.speechSynthesis.resume();state.paused=false;syncTaskbar();renderPanel();emit('resume',{});}}
function unlock(){saveEnabled(true);loadVoices(false);state.unlocked=true;speak(isAdminPath()?'เปิดเสียงภาษาไทยของ Sentinel Core แล้ว':'เปิดเสียงภาษาไทยของ Sentinel แล้ว',{force:true,profile:isAdminPath()?'sentinel-core':'sentinel'});}
function startListening(options={}){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('เบราว์เซอร์นี้ยังไม่รองรับการรู้จำเสียงภาษาไทย');emit('listen-error',{error:'speech_recognition_not_supported'});return null;}const recognition=new SR();recognition.lang=THAI_LOCALE;recognition.interimResults=!!options.interimResults;recognition.continuous=!!options.continuous;recognition.onstart=()=>emit('user-start',{lang:THAI_LOCALE});recognition.onend=()=>emit('user-end',{lang:THAI_LOCALE});recognition.onerror=(event)=>emit('listen-error',{error:event.error||'recognition_error'});recognition.onresult=(event)=>{const result=event.results[event.results.length-1];const transcript=result&&result[0]?String(result[0].transcript||'').trim():'';emit('user-result',{text:transcript,confidence:result&&result[0]?result[0].confidence:null});const target=options.targetInput||document.activeElement;if(transcript&&target&&('value'in target)){target.value=transcript;target.dispatchEvent(new Event('input',{bubbles:true}));}if(transcript&&options.autoSubmit){setTimeout(()=>{try{options.autoSubmit(transcript);}catch(error){emit('listen-error',{error:error.message});}},0);}};recognition.start();return recognition;}
function status(){loadVoices(false);return {...state,profiles:PROFILE,voice:state.activeVoice?{name:state.activeVoice.name,lang:state.activeVoice.lang,voiceURI:state.activeVoice.voiceURI}:null,thaiVoiceAvailable:thaiVoiceAvailable()};}
function escapeHtml(value){return String(value||'').replace(/[&<>"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function escapeAttr(value){return escapeHtml(value).replace(/'/g,'&#39;');}
function ensurePanelStyle(){if(document.getElementById('panthorium-voice-style'))return;const style=document.createElement('style');style.id='panthorium-voice-style';style.textContent=`#panthorium-voice-panel{position:fixed;right:18px;bottom:62px;width:min(420px,calc(100vw - 28px));max-height:min(620px,calc(100vh - 88px));z-index:10070;background:#08111d;color:#e8f0ff;border:1px solid rgba(0,255,204,.25);border-radius:16px;box-shadow:0 24px 80px rgba(0,0,0,.65);overflow:hidden;display:flex;flex-direction:column}#panthorium-voice-panel .voice-head{display:flex;align-items:center;justify-content:space-between;padding:13px 16px;border-bottom:1px solid rgba(255,255,255,.08);background:rgba(0,255,204,.06)}#panthorium-voice-panel .voice-head strong{font-size:15px;color:#00ffcc}#panthorium-voice-panel button{border:1px solid rgba(255,255,255,.12);background:#122036;color:#e8f0ff;border-radius:10px;padding:9px 11px;cursor:pointer}#panthorium-voice-panel button:hover{border-color:rgba(0,255,204,.45);color:#00ffcc}#panthorium-voice-panel .voice-body{padding:14px;overflow:auto;display:grid;gap:12px}#panthorium-voice-panel .voice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}#panthorium-voice-panel .voice-card{background:#0f1c2e;border:1px solid rgba(255,255,255,.06);border-radius:12px;padding:10px;display:grid;gap:4px}#panthorium-voice-panel small{color:#8a9bb8}#panthorium-voice-panel strong{font-size:18px}#panthorium-voice-panel .voice-row{display:flex;align-items:center;justify-content:space-between;gap:10px;background:#0c1727;border:1px solid rgba(255,255,255,.06);border-radius:12px;padding:10px;font-size:13px}#panthorium-voice-panel select,#panthorium-voice-panel input[type=range]{max-width:190px;width:48%;background:#101c2e;color:#e8f0ff;border:1px solid rgba(255,255,255,.12);border-radius:8px;padding:7px}#panthorium-voice-panel .voice-actions{display:flex;gap:8px;flex-wrap:wrap}#panthorium-voice-panel .voice-note{font-size:12px;color:#8a9bb8;line-height:1.55;margin:0}.panthorium-voice-chatbar{display:flex;gap:6px;padding:0 8px 8px;align-items:center}.panthorium-voice-chatbar button{border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.06);color:#e8f0ff;border-radius:8px;padding:7px 9px;cursor:pointer}.panthorium-voice-chatbar button.active{border-color:rgba(0,255,204,.55);color:#00ffcc}`;document.head.appendChild(style);}
function renderPanel(){const root=document.getElementById('panthorium-voice-panel');if(!root)return;loadVoices(false);const thai=thaiVoiceAvailable();const voiceOptions=state.voices.map(v=>`<option value="${escapeAttr(v.voiceURI||v.name)}" ${(state.activeVoice&&(state.activeVoice.voiceURI===v.voiceURI||state.activeVoice.name===v.name))?'selected':''}>${escapeHtml(v.name)} · ${escapeHtml(v.lang||'unknown')}</option>`).join('');root.querySelector('.voice-body').innerHTML=`<div class="voice-grid"><div class="voice-card"><small>TTS</small><strong>${state.supported?'พร้อมใช้งาน':'ไม่รองรับ'}</strong></div><div class="voice-card"><small>Thai voice</small><strong>${thai?'พบเสียงไทย':'ใช้ fallback'}</strong></div><div class="voice-card"><small>Auto speak</small><strong>${state.autoSpeak?'ON':'OFF'}</strong></div><div class="voice-card"><small>Now</small><strong>${state.speaking?'กำลังพูด':'เงียบ'}</strong></div></div><label class="voice-row"><span>เปิดเสียง AI อัตโนมัติ</span><input id="voice-enabled" type="checkbox" ${state.enabled?'checked':''}></label><label class="voice-row"><span>พูดคำตอบใหม่อัตโนมัติ</span><input id="voice-auto" type="checkbox" ${state.autoSpeak?'checked':''}></label><label class="voice-row"><span>เสียง</span><select id="voice-select">${voiceOptions||'<option>ไม่มีรายการเสียงจากเบราว์เซอร์</option>'}</select></label><label class="voice-row"><span>ความเร็ว</span><input id="voice-rate" type="range" min="0.55" max="1.35" step="0.01" value="${num(localStorage.getItem(KEYS.rate),.95,.55,1.35)}"></label><label class="voice-row"><span>ระดับเสียง</span><input id="voice-volume" type="range" min="0" max="1" step="0.01" value="${num(localStorage.getItem(KEYS.volume),1,0,1)}"></label><div class="voice-actions"><button id="voice-unlock">🔓 เปิด/ปลดล็อกเสียง</button><button id="voice-test-sentinel">🤖 ทดสอบ Sentinel</button><button id="voice-test-core">🛡️ ทดสอบ Core</button><button id="voice-stop">⏹ หยุดพูด</button></div><p class="voice-note">Sentinel Core ใช้โปรไฟล์เสียงหลังบ้านบน /admin ส่วน Sentinel ใช้โปรไฟล์เสียงผู้ใช้ทั่วไปที่หน้า / และทั้งคู่ตั้งค่าเป็นภาษาไทย th-TH</p>`;root.querySelector('#voice-enabled').onchange=(e)=>saveEnabled(e.target.checked);root.querySelector('#voice-auto').onchange=(e)=>saveAuto(e.target.checked);root.querySelector('#voice-select').onchange=(e)=>{localStorage.setItem(KEYS.voice,e.target.value);loadVoices();};root.querySelector('#voice-rate').oninput=(e)=>localStorage.setItem(KEYS.rate,e.target.value);root.querySelector('#voice-volume').oninput=(e)=>localStorage.setItem(KEYS.volume,e.target.value);root.querySelector('#voice-unlock').onclick=unlock;root.querySelector('#voice-test-sentinel').onclick=()=>speakSentinel('สวัสดีครับ ฉันคือ Sentinel พร้อมพูดภาษาไทยแล้ว',{force:true});root.querySelector('#voice-test-core').onclick=()=>speakCore('Sentinel Core พร้อมดูแลระบบหลังบ้านด้วยเสียงภาษาไทยแล้ว',{force:true});root.querySelector('#voice-stop').onclick=stop;}
function openPanel(){ensurePanelStyle();let root=document.getElementById('panthorium-voice-panel');if(root){root.style.display='flex';renderPanel();return;}root=document.createElement('div');root.id='panthorium-voice-panel';root.innerHTML='<div class="voice-head"><strong>🔊 Thai Voice I/O</strong><button id="voice-close" title="ปิด">×</button></div><div class="voice-body">Loading…</div>';document.body.appendChild(root);root.querySelector('#voice-close').onclick=()=>{root.style.display='none';};loadVoices(false);renderPanel();}
function syncTaskbar(){const btn=document.getElementById('panthorium-voice-taskbar');if(btn){btn.textContent=state.speaking?'🔊':(state.enabled?'🔈':'🔇');btn.title=`Thai Voice I/O · ${state.enabled?'ON':'OFF'}`;}}
function installTaskbarButton(){if(document.getElementById('panthorium-voice-taskbar'))return true;const host=document.querySelector('.tb-right')||document.getElementById('taskbar');if(!host)return false;const btn=document.createElement('button');btn.id='panthorium-voice-taskbar';btn.className='tb-btn';btn.type='button';btn.onclick=openPanel;host.insertBefore(btn,host.firstChild);syncTaskbar();return true;}
function enhanceSentinelWindow(){const container=document.querySelector('.chat-container');if(!container||container.querySelector('.panthorium-voice-chatbar'))return;const bar=document.createElement('div');bar.className='panthorium-voice-chatbar';bar.innerHTML='<button type="button" data-voice-toggle>🔊 เปิดเสียงไทย</button><button type="button" data-voice-stop>⏹ หยุด</button><button type="button" data-voice-settings>⚙️ Voice</button>';container.insertBefore(bar,container.firstChild);const toggle=bar.querySelector('[data-voice-toggle]');const refresh=()=>{toggle.classList.toggle('active',state.enabled);toggle.textContent=state.enabled?'🔊 ปิดเสียงไทย':'🔇 เปิดเสียงไทย';};toggle.onclick=()=>{if(state.enabled){saveEnabled(false);stop();}else unlock();refresh();};bar.querySelector('[data-voice-stop]').onclick=stop;bar.querySelector('[data-voice-settings]').onclick=openPanel;refresh();}
function wrapOpenSentinel(){if(typeof window.openSentinel!=='function')return false;if(window.openSentinel.__thaiVoiceWrapped)return true;const original=window.openSentinel;window.openSentinel=function(...args){const result=original.apply(this,args);setTimeout(enhanceSentinelWindow,0);return result;};window.openSentinel.__thaiVoiceWrapped=true;return true;}
function installSpeakBridge(){const previous=window.speak;if(previous&&previous.__thaiVoiceBridge)return;const bridged=function(text,options={}){return speak(text,options);};bridged.__thaiVoiceBridge=true;window.speak=bridged;}
function install(){loadVoices(false);if(state.supported)window.speechSynthesis.onvoiceschanged=()=>loadVoices();installSpeakBridge();let attempts=0;const timer=setInterval(()=>{attempts+=1;const ok1=installTaskbarButton();const ok2=wrapOpenSentinel();if((ok1&&ok2)||attempts>60)clearInterval(timer);},100);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{installTaskbarButton();wrapOpenSentinel();},{once:true});else{installTaskbarButton();wrapOpenSentinel();}window.addEventListener('panthorium:ai-done',(event)=>{if(!state.autoSpeak)return;const d=event.detail||{};speak(d.text||d.message||'',{provider:d.provider,source:'ai-done'});});window.addEventListener('panthorium:auth-changed',()=>setTimeout(()=>{installTaskbarButton();wrapOpenSentinel();},50));}

window.PanthoriumVoice={status,speak,speakCore,speakSentinel,stop,pause,resume,unlock,enable:saveEnabled,setAutoSpeak:saveAuto,listen:startListening,open:openPanel,cleanText,loadVoices,profiles:PROFILE};
install();
})();
