const express = require("express");
const rateLimit = require("express-rate-limit");
const { randomUUID } = require("crypto");
const { requireAuth, requirePermission } = require("../middleware/auth");
function validText(value,max){return typeof value==="string"&&value.trim().length>0&&value.length<=max;}
function validChatBody(body={}){if(!validText(body.message,8000))return"invalid_message";if(body.sessionId!=null&&(typeof body.sessionId!=="string"||body.sessionId.length>120))return"invalid_session_id";if(body.provider!=null&&(typeof body.provider!=="string"||body.provider.length>40))return"invalid_provider";if(body.model!=null&&(typeof body.model!=="string"||body.model.length>120))return"invalid_model";return null;}
function createApiRouter(sentinelCore,authService,audit,aiOperations,agentService,agentPlanner,agentWorkflow,agentRuns,agentScheduler,agentAutomation,multiAgent){
 const router=express.Router();const auth=requireAuth(authService);const aiLimiter=rateLimit({windowMs:60000,limit:30,standardHeaders:true,legacyHeaders:false});const agentLimiter=rateLimit({windowMs:60000,limit:60,standardHeaders:true,legacyHeaders:false});
 router.get("/health",(req,res)=>res.json({ok:true,service:"Panthorium Backend",core:sentinelCore.status(),time:new Date().toISOString()}));
 router.get("/core/status",auth,requirePermission("system:read"),(req,res)=>res.json({ok:true,...sentinelCore.status()}));
 router.get("/ai/providers",auth,requirePermission("chat"),(req,res)=>res.json({ok:true,providers:sentinelCore.providerCatalog()}));
 router.get("/ai/operations",auth,requirePermission("chat"),async(req,res,next)=>{try{res.json({ok:true,metrics:await aiOperations.overview(req.user.sub,req.query.hours)});}catch(e){next(e);}});
 router.get("/agent/tools",auth,agentLimiter,(req,res)=>res.json({ok:true,tools:agentService.catalogFor(req.user)}));
 router.get("/agent/orchestration/roles",auth,requirePermission("chat"),agentLimiter,(req,res)=>{const r=multiAgent.listRoles(req.user);res.status(r.ok?200:403).json(r);});
 router.get("/agent/orchestration/runs",auth,requirePermission("chat"),agentLimiter,async(req,res,next)=>{try{res.json(await multiAgent.history(req.user,Number(req.query.limit)||30));}catch(e){next(e);}});
 router.get("/agent/orchestration/runs/:id",auth,requirePermission("chat"),agentLimiter,async(req,res,next)=>{try{if(!validText(req.params.id,80))return res.status(400).json({ok:false,error:"invalid_orchestration_id"});const r=await multiAgent.get(req.user,req.params.id);res.status(r.ok?200:404).json(r);}catch(e){next(e);}});
 router.post("/agent/orchestration/run",auth,requirePermission("chat"),agentLimiter,async(req,res,next)=>{try{const{request,message,roles,provider}=req.body||{};const input=request||message;if(!validText(input,4000))return res.status(400).json({ok:false,error:"invalid_multi_agent_request"});if(roles!=null&&!Array.isArray(roles))return res.status(400).json({ok:false,error:"invalid_multi_agent_roles"});if(provider!=null&&!validText(provider,40))return res.status(400).json({ok:false,error:"invalid_provider"});const r=await multiAgent.run({user:req.user,request:input,roles,provider,requestId:req.requestId});res.status(r.status==="waiting_confirmation"?409:r.ok?200:422).json(r);}catch(e){next(e);}});
 router.get("/agent/runs",auth,requirePermission("chat"),agentLimiter,async(req,res,next)=>{try{res.json({ok:true,runs:await agentRuns.list(req.user.sub,Number(req.query.limit)||30)});}catch(e){next(e);}});
 router.get("/agent/jobs",auth,requirePermission("chat"),agentLimiter,async(req,res,next)=>{try{res.json({ok:true,jobs:await agentScheduler.list(req.user.sub,Number(req.query.limit)||30)});}catch(e){next(e);}});
 router.post("/agent/execute",auth,agentLimiter,async(req,res,next)=>{try{const{toolId,args,confirmed}=req.body||{};if(!validText(toolId,100))return res.status(400).json({ok:false,error:"invalid_tool_id"});const r=await agentService.execute({user:req.user,toolId,args:args||{},confirmed:confirmed===true,requestId:req.requestId});res.status(r.error==="confirmation_required"?409:r.ok?200:r.error==="tool_permission_denied"?403:400).json(r);}catch(e){next(e);}});
 router.post("/agent/plan",auth,requirePermission("chat"),agentLimiter,async(req,res,next)=>{try{const{request,message,provider}=req.body||{};const input=request||message;if(!validText(input,8000))return res.status(400).json({ok:false,error:"invalid_agent_request"});const r=await agentPlanner.plan({user:req.user,request:input,preferredProvider:provider?.toLowerCase(),requestId:req.requestId});res.status(r.ok?200:422).json(r);}catch(e){next(e);}});
 router.post("/agent/workflow/run",auth,requirePermission("chat"),agentLimiter,async(req,res,next)=>{try{const{request,message,provider}=req.body||{};const input=request||message;if(!validText(input,8000))return res.status(400).json({ok:false,error:"invalid_agent_request"});const r=await agentWorkflow.run({user:req.user,request:input,preferredProvider:provider?.toLowerCase(),requestId:req.requestId});res.status(r.confirmationRequired?409:r.ok?200:422).json(r);}catch(e){next(e);}});
 router.post("/agent/workflow/:workflowId/confirm",auth,requirePermission("chat"),agentLimiter,async(req,res,next)=>{try{const r=await agentWorkflow.confirm({user:req.user,workflowId:req.params.workflowId,requestId:req.requestId});res.status(r.confirmationRequired?409:r.ok?200:r.error==="workflow_not_found"?404:422).json(r);}catch(e){next(e);}});
 router.get("/conversations",auth,requirePermission("chat"),async(req,res)=>res.json({ok:true,sessions:await sentinelCore.conversationSessions(req.user.sub,Number(req.query.limit)||30)}));
 router.get("/conversations/:sessionId",auth,requirePermission("chat"),async(req,res)=>{if(!validText(req.params.sessionId,120))return res.status(400).json({ok:false,error:"invalid_session_id"});res.json({ok:true,sessionId:req.params.sessionId,messages:await sentinelCore.conversationHistory(req.user.sub,req.params.sessionId,Number(req.query.limit)||40)});});
 router.delete("/conversations/:sessionId",auth,requirePermission("chat"),async(req,res)=>{await sentinelCore.clearConversation(req.user.sub,req.params.sessionId);res.json({ok:true});});
 router.post("/chat",auth,requirePermission("chat"),aiLimiter,async(req,res)=>{try{const error=validChatBody(req.body||{});if(error)return res.status(400).json({ok:false,error});const{message,sessionId,mode,provider,model}=req.body||{};const sid=sessionId||randomUUID();const result=await sentinelCore.chat({sessionId:sid,userId:req.user.sub,message,mode:mode==="core"?"core":"default",provider:provider?.toLowerCase(),model});res.json({...result,sessionId:sid});}catch(e){res.status(500).json({ok:false,error:"internal_error"});}});
 router.post("/core/command",auth,requirePermission("core:command"),aiLimiter,async(req,res)=>{try{const{command,sessionId,provider,model}=req.body||{};if(!validText(command,8000))return res.status(400).json({ok:false,error:"invalid_command"});const sid=sessionId||randomUUID();const result=await sentinelCore.chat({sessionId:sid,userId:req.user.sub,message:command,mode:"core",provider:provider?.toLowerCase(),model});res.json({...result,sessionId:sid});}catch(e){res.status(500).json({ok:false,error:"internal_error"});}});
 router.post("/chat/clear",auth,requirePermission("chat"),async(req,res)=>{const{sessionId}=req.body||{};if(typeof sessionId==="string")await sentinelCore.clearConversation(req.user.sub,sessionId);res.json({ok:true});});return router;
}
module.exports={createApiRouter};
