const express=require('express');
const rateLimit=require('express-rate-limit');
const {requireAuth,requirePermission}=require('../middleware/auth');
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function validId(v){return typeof v==='string'&&UUID_RE.test(v);}
function createAutomationRouter(authService,automation){const r=express.Router();const auth=requireAuth(authService);const limiter=rateLimit({windowMs:60000,limit:60,standardHeaders:true,legacyHeaders:false});const eventLimiter=rateLimit({windowMs:60000,limit:20,standardHeaders:true,legacyHeaders:false,message:{ok:false,error:'automation_event_rate_limited'}});
r.get('/policy',auth,requirePermission('chat'),limiter,(req,res)=>res.json({ok:true,policy:automation.policyProfile(req.user)}));
r.get('/schedules',auth,requirePermission('chat'),limiter,async(req,res,next)=>{try{res.json({ok:true,schedules:await automation.listSchedules(req.user.sub,Number(req.query.limit)||30)});}catch(e){next(e);}});
r.post('/schedules',auth,requirePermission('chat'),limiter,async(req,res,next)=>{try{const {request,message,provider,firstRunAt,everyMinutes,maxRuns}=req.body||{};const out=await automation.createSchedule({user:req.user,request:request||message,provider,firstRunAt,everyMinutes,maxRuns,requestId:req.requestId});const denied=String(out.error||'').startsWith('automation_');res.status(out.ok?201:denied?403:400).json(out);}catch(e){next(e);}});
r.delete('/schedules/:scheduleId',auth,requirePermission('chat'),limiter,async(req,res,next)=>{try{if(!validId(req.params.scheduleId))return res.status(400).json({ok:false,error:'invalid_schedule_id'});const out=await automation.disableSchedule({user:req.user,scheduleId:req.params.scheduleId,requestId:req.requestId});res.status(out.ok?200:out.error==='automation_requires_account'||out.error==='automation_permission_denied'?403:404).json(out);}catch(e){next(e);}});
r.get('/triggers',auth,requirePermission('chat'),limiter,async(req,res,next)=>{try{res.json({ok:true,triggers:await automation.listTriggers(req.user.sub,Number(req.query.limit)||30)});}catch(e){next(e);}});
r.post('/triggers',auth,requirePermission('chat'),limiter,async(req,res,next)=>{try{const {eventKey,request,message,provider}=req.body||{};const out=await automation.createTrigger({user:req.user,eventKey,request:request||message,provider,requestId:req.requestId});const denied=String(out.error||'').startsWith('automation_');res.status(out.ok?201:denied?403:400).json(out);}catch(e){next(e);}});
r.delete('/triggers/:triggerId',auth,requirePermission('chat'),limiter,async(req,res,next)=>{try{if(!validId(req.params.triggerId))return res.status(400).json({ok:false,error:'invalid_trigger_id'});const out=await automation.disableTrigger({user:req.user,triggerId:req.params.triggerId,requestId:req.requestId});res.status(out.ok?200:out.error==='automation_requires_account'||out.error==='automation_permission_denied'?403:404).json(out);}catch(e){next(e);}});
r.post('/events/:eventKey',auth,requirePermission('chat'),eventLimiter,async(req,res,next)=>{try{const out=await automation.emit({user:req.user,eventKey:req.params.eventKey,payload:req.body?.payload,requestId:req.requestId});res.status(out.ok?202:String(out.error||'').startsWith('automation_')?403:400).json(out);}catch(e){next(e);}});
return r;}
module.exports={createAutomationRouter};