const express=require('express');const rateLimit=require('express-rate-limit');const{requireAuth,requirePermission}=require('../middleware/auth');
function createTrainingRouter(authService,training,benchmark){
 const router=express.Router(),auth=requireAuth(authService),readLimiter=rateLimit({windowMs:60000,limit:60,standardHeaders:true,legacyHeaders:false}),teacherLimiter=rateLimit({windowMs:60000,limit:6,standardHeaders:true,legacyHeaders:false}),benchmarkLimiter=rateLimit({windowMs:60000,limit:2,standardHeaders:true,legacyHeaders:false}),admin=[auth,requirePermission('settings')];
 router.get('/status',...admin,readLimiter,async(req,res,next)=>{try{res.json(await training.list({limit:1}));}catch(e){next(e);}});
 router.get('/examples',...admin,readLimiter,async(req,res,next)=>{try{res.json(await training.list({status:req.query.status,limit:req.query.limit}));}catch(e){next(e);}});
 router.post('/examples',...admin,readLimiter,async(req,res,next)=>{try{const r=await training.addExample({...req.body,user:req.user,requestId:req.requestId});res.status(r.ok?201:400).json(r);}catch(e){next(e);}});
 router.post('/teachers/draft',...admin,teacherLimiter,async(req,res,next)=>{try{const r=await training.draftWithTeachers({prompt:req.body?.prompt,providerNames:req.body?.providers,tags:req.body?.tags,user:req.user,requestId:req.requestId});res.status(r.ok?201:r.error==='no_teacher_provider'?409:400).json(r);}catch(e){next(e);}});
 router.post('/auto/run',...admin,teacherLimiter,async(req,res,next)=>{try{const r=await training.autoProcessPending({limit:req.body?.limit});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/examples/:exampleId/approve',...admin,readLimiter,async(req,res,next)=>{try{const r=await training.review({exampleId:req.params.exampleId,status:'approved',user:req.user,requestId:req.requestId});res.status(r.ok?200:404).json(r);}catch(e){next(e);}});
 router.post('/examples/:exampleId/reject',...admin,readLimiter,async(req,res,next)=>{try{const r=await training.review({exampleId:req.params.exampleId,status:'rejected',user:req.user,requestId:req.requestId});res.status(r.ok?200:404).json(r);}catch(e){next(e);}});
 router.get('/learning/status',...admin,readLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});res.json(await training.learning.status());}catch(e){next(e);}});
 router.get('/learning/versions',...admin,readLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});res.json({ok:true,versions:await training.learning.repository.list({state:req.query.state,limit:req.query.limit})});}catch(e){next(e);}});
 router.post('/learning/:versionId/shadow',...admin,teacherLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});const r=await training.learning.recordShadow(req.params.versionId,{score:req.body?.score,safe:req.body?.safe!==false,criticalSafetyEvent:req.body?.criticalSafetyEvent===true,metadata:{source:'training-api',requestId:req.requestId}});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/learning/:versionId/promote',...admin,teacherLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});const r=await training.learning.promoteIfReady(req.params.versionId);res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/learning/:versionId/monitor',...admin,teacherLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});const r=await training.learning.monitor(req.params.versionId,{rollingScore:req.body?.rollingScore,baselineScore:req.body?.baselineScore,criticalSafetyEvent:req.body?.criticalSafetyEvent===true});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/learning/:versionId/rollback',...admin,teacherLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});const r=await training.learning.rollback(req.params.versionId,{reason:'administrator_requested_rollback',autoRecover:req.body?.autoRecover===true});res.status(r.ok?200:404).json(r);}catch(e){next(e);}});
 router.post('/learning/:versionId/recover',...admin,teacherLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});const r=await training.learning.recover(req.params.versionId);res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.get('/benchmark/status',...admin,readLimiter,async(req,res,next)=>{try{if(!benchmark)return res.status(503).json({ok:false,error:'benchmark_unavailable'});res.json(benchmark.status());}catch(e){next(e);}});
 router.post('/benchmark/run',...admin,benchmarkLimiter,async(req,res,next)=>{try{if(!benchmark)return res.status(503).json({ok:false,error:'benchmark_unavailable'});const r=await benchmark.run({cases:req.body?.cases,providerNames:req.body?.providers,userId:req.user?.sub||'system'});res.status(r.ok?200:400).json(r);}catch(e){next(e);}});
 router.get('/export.jsonl',...admin,readLimiter,async(req,res,next)=>{try{const data=await training.exportJsonl();res.set('Content-Type','application/x-ndjson; charset=utf-8');res.set('Content-Disposition','attachment; filename="sentinel-training.jsonl"');res.send(data?`${data}\n`:'');}catch(e){next(e);}});return router;
}
module.exports={createTrainingRouter};
