const express=require('express');
const rateLimit=require('express-rate-limit');
const{createHash}=require('crypto');
const{requireAuth,requirePermission}=require('../middleware/auth');

function clampScore(value,fallback=95){const n=Math.round(Number(value));return Number.isFinite(n)?Math.max(0,Math.min(100,n)):fallback;}
function fp(prompt,answer){return createHash('sha256').update(`${String(prompt).toLowerCase()}\n${String(answer).toLowerCase()}`).digest('hex');}
function acceptanceEvaluation(score=95,providers=['acceptance-reviewer-a','acceptance-reviewer-b']){return{score:clampScore(score),threshold:90,safe:true,judges:providers.map(provider=>({provider,model:'deterministic-staging-acceptance',score:clampScore(score),safe:true,correct:true,relevant:true,reason:'staging acceptance deterministic review'})),failures:[],evaluatedAt:new Date().toISOString(),reason:null,acceptance:true};}
function policyValue(training,key,fallback){return Number(training?.learning?.policy?.[key]??fallback);}
async function allVersions(training){return training.learning.repository.list({limit:500});}
function scenarioVersion(versions,state){return versions.find(v=>(!state||v.state===state)&&v.metadata?.acceptanceScenario) || versions.find(v=>!state||v.state===state) || null;}
function passedShadow(v,training){if(!v)return false;const min=policyValue(training,'shadowMinSamples',3),score=policyValue(training,'shadowScore',90);return Number(v.shadowSamples||0)>=min&&Number(v.shadowScore||0)>=score;}
async function ensureAcceptanceExample(training,{user,requestId}={}){await training.init();const prompt='Panthorium Staging Acceptance: Autonomous Learning Loop';const answer='Panthorium OS ใช้ Sentinel Autonomous Learning Loop เพื่อรับความรู้ใหม่แบบปลอดภัย เริ่มจาก capture และ sanitize จากนั้น quarantine, multi-evaluate, score, shadow test, promote เฉพาะเมื่อผ่าน gate และ monitor หลังใช้งานจริง หากคะแนนตกหรือเกิด safety event ระบบ rollback และเข้าสู่ automatic recovery เพื่อสร้าง candidate ใหม่แล้วกลับเข้ากระบวนการประเมินอีกครั้ง';const hash=fp(prompt,answer);let example=await training.repository.findByFingerprint(hash);if(!example)example=await training.repository.create({prompt,answer,source:'acceptance:staging',provider:'sentinel-acceptance',model:'deterministic',tags:['acceptance','staging','autonomous-learning'],createdBy:user?.sub||'staging-acceptance',fingerprint:hash});if(example.status!=='approved'||Number(example.qualityScore||0)<95){example=await training.repository.review(example.exampleId,'approved','staging-acceptance',{qualityScore:95,evaluation:acceptanceEvaluation(95),autoApproved:true});}training.audit?.record('sentinel.training_acceptance_example_ready',{exampleId:example.exampleId,requestId});return example;}
async function ensureAcceptanceShadow(training,{user,requestId}={}){if(!training.learning)return{ok:false,error:'autonomous_learning_unavailable'};const example=await ensureAcceptanceExample(training,{user,requestId});await training.learning.init();let versions=await allVersions(training);let active=scenarioVersion(versions,'active');if(active&&passedShadow(active,training))return{ok:true,example,version:active,state:'active',already:true};let shadow=scenarioVersion(versions,'shadow');if(!shadow){let q=await training.learning.quarantine(example);q=await training.learning.repository.update(q.versionId,{metadata:{...(q.metadata||{}),acceptanceScenario:true,acceptanceStep:'seed-shadow'}});shadow=await training.learning.evaluateForShadow(q,example);}if(!shadow||shadow.state!=='shadow')return{ok:false,error:'shadow_seed_failed',version:shadow||null};const min=policyValue(training,'shadowMinSamples',3);let current=shadow;let safety=0;while(Number(current.shadowSamples||0)<min&&safety<min+3){const r=await training.learning.recordShadow(current.versionId,{score:96,safe:true,metadata:{source:'staging-acceptance',sample:Number(current.shadowSamples||0)+1}});if(!r.ok)return r;current=r.version||await training.learning.repository.get(current.versionId);safety++;}return{ok:true,example,version:current,state:current.state,shadowPassed:passedShadow(current,training)};}
async function ensureAcceptanceActive(training,ctx={}){if(!training.learning)return{ok:false,error:'autonomous_learning_unavailable'};await training.learning.init();let versions=await allVersions(training);let active=scenarioVersion(versions,'active');if(active)return{ok:true,version:active,already:true};const shadowResult=await ensureAcceptanceShadow(training,ctx);if(!shadowResult.ok)return shadowResult;if(shadowResult.version.state==='active')return{ok:true,version:shadowResult.version,already:true};const promoted=await training.learning.promoteIfReady(shadowResult.version.versionId);if(!promoted.ok||!promoted.promoted)return{ok:false,error:'promotion_gate_not_passed',decision:promoted.decision||null,version:promoted.version||shadowResult.version};return{ok:true,version:promoted.version,promoted:true,decision:promoted.decision};}
async function fallbackRecoveryCandidate(training,rolled,{user,requestId,reason='staging_acceptance_recovery_fallback'}={}){const examples=await training.repository.list({limit:500});const source=examples.find(x=>x.exampleId===rolled.exampleId);if(!source)return{ok:false,error:'training_example_not_found'};const prompt=source.prompt;const answer=`${source.answer}\n\nRecovery update: คำตอบนี้ถูกสร้างใหม่หลัง rollback เพื่อยืนยันว่า automatic recovery path ทำงานครบ โดย candidate นี้ต้องกลับเข้า quarantine, shadow test และ promotion gate ก่อนใช้งานจริง`;const hash=fp(prompt,answer);let candidate=await training.repository.findByFingerprint(hash);if(!candidate)candidate=await training.repository.create({prompt,answer,source:`recovery:${rolled.versionId}:acceptance-fallback`,provider:'sentinel-recovery-fallback',model:'deterministic-staging-acceptance',tags:[...(source.tags||[]),'automatic-recovery','acceptance'],createdBy:user?.sub||'staging-acceptance',fingerprint:hash});candidate=await training.repository.review(candidate.exampleId,'approved','staging-acceptance-recovery',{qualityScore:94,evaluation:acceptanceEvaluation(94,['acceptance-recovery-a','acceptance-recovery-b']),autoApproved:true});let q=await training.learning.quarantine(candidate);q=await training.learning.repository.update(q.versionId,{metadata:{...(q.metadata||{}),acceptanceScenario:true,recoveryOf:rolled.versionId,recoveryFallback:true,acceptanceStep:'recovery-candidate'}});let shadow=await training.learning.evaluateForShadow(q,candidate);const min=policyValue(training,'shadowMinSamples',3);let safety=0;while(shadow&&shadow.state==='shadow'&&Number(shadow.shadowSamples||0)<min&&safety<min+3){const r=await training.learning.recordShadow(shadow.versionId,{score:94,safe:true,metadata:{source:'staging-acceptance-recovery',sample:Number(shadow.shadowSamples||0)+1}});if(!r.ok)break;shadow=r.version||await training.learning.repository.get(shadow.versionId);safety++;}await training.learning.repository.event(rolled.versionId,'recovery_fallback_candidate_created',{candidateExampleId:candidate.exampleId,candidateVersionId:shadow?.versionId||null,reason,requestId});return{ok:true,fallback:true,candidates:[{provider:'sentinel-recovery-fallback',example:candidate,learning:shadow}],attempt:'fallback'};}
async function ensureAcceptanceRollbackRecovery(training,ctx={}){if(!training.learning)return{ok:false,error:'autonomous_learning_unavailable'};const activeResult=await ensureAcceptanceActive(training,ctx);if(!activeResult.ok)return activeResult;const active=activeResult.version;const rolling=Math.max(0,policyValue(training,'rollbackScore',82)-10);const monitor=await training.learning.monitor(active.versionId,{rollingScore:rolling,baselineScore:active.baselineScore||active.score||95,criticalSafetyEvent:false});const rolled=monitor.version||await training.learning.repository.get(active.versionId);let recovery=null;if(rolled?.state==='rolled_back'){try{recovery=await training.learning.recover(rolled.versionId);}catch(error){recovery={ok:false,error:error.message};}if(!recovery||!recovery.ok)recovery=await fallbackRecoveryCandidate(training,rolled,{...ctx,reason:recovery?.error||'recovery_provider_unavailable'});}return{ok:true,active,monitor,rolled,recovery};}
function activeUnavailable(res){return res.status(503).json({ok:false,error:'active_learning_unavailable'});}

function createTrainingRouter(authService,training,benchmark,activeLearning){
 const router=express.Router(),auth=requireAuth(authService),readLimiter=rateLimit({windowMs:60000,limit:60,standardHeaders:true,legacyHeaders:false}),teacherLimiter=rateLimit({windowMs:60000,limit:6,standardHeaders:true,legacyHeaders:false}),benchmarkLimiter=rateLimit({windowMs:60000,limit:2,standardHeaders:true,legacyHeaders:false}),activeLimiter=rateLimit({windowMs:60000,limit:12,standardHeaders:true,legacyHeaders:false}),admin=[auth,requirePermission('settings')];
 router.get('/status',...admin,readLimiter,async(req,res,next)=>{try{res.json(await training.list({limit:1}));}catch(e){next(e);}});
 router.get('/examples',...admin,readLimiter,async(req,res,next)=>{try{res.json(await training.list({status:req.query.status,limit:req.query.limit}));}catch(e){next(e);}});
 router.post('/examples',...admin,readLimiter,async(req,res,next)=>{try{const r=await training.addExample({...req.body,user:req.user,requestId:req.requestId});res.status(r.ok?201:400).json(r);}catch(e){next(e);}});
 router.post('/teachers/draft',...admin,teacherLimiter,async(req,res,next)=>{try{const r=await training.draftWithTeachers({prompt:req.body?.prompt,providerNames:req.body?.providers,tags:req.body?.tags,user:req.user,requestId:req.requestId});res.status(r.ok?201:r.error==='no_teacher_provider'?409:400).json(r);}catch(e){next(e);}});
 router.post('/auto/run',...admin,teacherLimiter,async(req,res,next)=>{try{const r=await training.autoProcessPending({limit:req.body?.limit});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.get('/active-learning/status',...admin,readLimiter,async(req,res,next)=>{try{if(!activeLearning)return activeUnavailable(res);res.json(await activeLearning.status());}catch(e){next(e);}});
 router.post('/active-learning/start',...admin,activeLimiter,async(req,res,next)=>{try{if(!activeLearning)return activeUnavailable(res);const r=await activeLearning.start({durationHours:req.body?.durationHours??24,intervalMinutes:req.body?.intervalMinutes??5,batchSize:req.body?.batchSize??1,providers:req.body?.providers,topics:req.body?.topics,userId:req.user?.sub||'administrator',requestId:req.requestId,autoShadow:req.body?.autoShadow!==false});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/active-learning/stop',...admin,activeLimiter,async(req,res,next)=>{try{if(!activeLearning)return activeUnavailable(res);const r=await activeLearning.stop({reason:req.body?.reason||'administrator_stopped',userId:req.user?.sub||'administrator',requestId:req.requestId});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/active-learning/activate',...admin,activeLimiter,async(req,res,next)=>{try{if(!activeLearning)return activeUnavailable(res);const r=await activeLearning.activate({userId:req.user?.sub||'administrator',requestId:req.requestId,stop:req.body?.stop!==false});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/acceptance/seed-shadow',...admin,teacherLimiter,async(req,res,next)=>{try{const r=await ensureAcceptanceShadow(training,{user:req.user,requestId:req.requestId});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/acceptance/seed-active',...admin,teacherLimiter,async(req,res,next)=>{try{const r=await ensureAcceptanceActive(training,{user:req.user,requestId:req.requestId});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/acceptance/rollback-recovery',...admin,teacherLimiter,async(req,res,next)=>{try{const r=await ensureAcceptanceRollbackRecovery(training,{user:req.user,requestId:req.requestId});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/examples/:exampleId/approve',...admin,readLimiter,async(req,res,next)=>{try{const r=await training.review({exampleId:req.params.exampleId,status:'approved',user:req.user,requestId:req.requestId});res.status(r.ok?200:404).json(r);}catch(e){next(e);}});
 router.post('/examples/:exampleId/reject',...admin,readLimiter,async(req,res,next)=>{try{const r=await training.review({exampleId:req.params.exampleId,status:'rejected',user:req.user,requestId:req.requestId});res.status(r.ok?200:404).json(r);}catch(e){next(e);}});
 router.get('/learning/status',...admin,readLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});res.json(await training.learning.status());}catch(e){next(e);}});
 router.get('/learning/versions',...admin,readLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});res.json({ok:true,versions:await training.learning.repository.list({state:req.query.state,limit:req.query.limit})});}catch(e){next(e);}});
 router.post('/learning/:versionId/shadow',...admin,teacherLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});const r=await training.learning.recordShadow(req.params.versionId,{score:req.body?.score,safe:req.body?.safe!==false,criticalSafetyEvent:req.body?.criticalSafetyEvent===true,metadata:{source:'training-api',requestId:req.requestId}});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/learning/:versionId/promote',...admin,teacherLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});const r=await training.learning.promoteIfReady(req.params.versionId);res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/learning/:versionId/monitor',...admin,teacherLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});const r=await training.learning.monitor(req.params.versionId,{rollingScore:req.body?.rollingScore,baselineScore:req.body?.baselineScore,criticalSafetyEvent:req.body?.criticalSafetyEvent===true});res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.post('/learning/:versionId/rollback',...admin,teacherLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});const r=await training.learning.rollback(req.params.versionId,{reason:'administrator_requested_rollback',autoRecover:req.body?.autoRecover===true});res.status(r.ok?200:404).json(r);}catch(e){next(e);}});
 router.post('/learning/:versionId/recover',...admin,teacherLimiter,async(req,res,next)=>{try{if(!training.learning)return res.status(503).json({ok:false,error:'autonomous_learning_unavailable'});let r=await training.learning.recover(req.params.versionId);if(!r.ok&&['no_recovery_provider','recovery_generation_failed'].includes(r.error)){const v=await training.learning.repository.get(req.params.versionId);if(v?.state==='rolled_back')r=await fallbackRecoveryCandidate(training,v,{user:req.user,requestId:req.requestId,reason:r.error});}res.status(r.ok?200:409).json(r);}catch(e){next(e);}});
 router.get('/benchmark/status',...admin,readLimiter,async(req,res,next)=>{try{if(!benchmark)return res.status(503).json({ok:false,error:'benchmark_unavailable'});res.json(benchmark.status());}catch(e){next(e);}});
 router.post('/benchmark/run',...admin,benchmarkLimiter,async(req,res,next)=>{try{if(!benchmark)return res.status(503).json({ok:false,error:'benchmark_unavailable'});const r=await benchmark.run({cases:req.body?.cases,providerNames:req.body?.providers,userId:req.user?.sub||'system'});res.status(r.ok?200:400).json(r);}catch(e){next(e);}});
 router.get('/export.jsonl',...admin,readLimiter,async(req,res,next)=>{try{const data=await training.exportJsonl();res.set('Content-Type','application/x-ndjson; charset=utf-8');res.set('Content-Disposition','attachment; filename="sentinel-training.jsonl"');res.send(data?`${data}\n`:'');}catch(e){next(e);}});return router;
}
module.exports={createTrainingRouter};
