const { randomUUID } = require('crypto');
const { Pool } = require('pg');
class AgentKnowledgeRepository {
  constructor({ databaseUrl, databaseSslMode } = {}) { this.pool = databaseUrl ? new Pool({ connectionString: databaseUrl, ssl: databaseSslMode === 'disable' ? false : { rejectUnauthorized: false } }) : null; this.docs = new Map(); this.chunks = new Map(); }
  async init() { if (!this.pool) return; await this.pool.query(`CREATE TABLE IF NOT EXISTS panthorium_knowledge_documents (document_id UUID PRIMARY KEY,user_id TEXT NOT NULL,title TEXT NOT NULL,source TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_panthorium_knowledge_user ON panthorium_knowledge_documents(user_id,created_at DESC); CREATE TABLE IF NOT EXISTS panthorium_knowledge_chunks (chunk_id UUID PRIMARY KEY,document_id UUID NOT NULL REFERENCES panthorium_knowledge_documents(document_id) ON DELETE CASCADE,user_id TEXT NOT NULL,chunk_index INTEGER NOT NULL,content TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_panthorium_knowledge_chunks_user ON panthorium_knowledge_chunks(user_id,document_id,chunk_index);`); }
  mapDoc(r) { return { documentId:r.document_id,userId:r.user_id,title:r.title,source:r.source,metadata:r.metadata||{},createdAt:r.created_at,updatedAt:r.updated_at }; }
  mapChunk(r) { return { chunkId:r.chunk_id,documentId:r.document_id,userId:r.user_id,chunkIndex:r.chunk_index,content:r.content,createdAt:r.created_at }; }
  async create({ userId,title,source,metadata,chunks }) { const documentId=randomUUID(); const now=new Date().toISOString(); if(this.pool){const c=await this.pool.connect();try{await c.query('BEGIN');await c.query('INSERT INTO panthorium_knowledge_documents(document_id,user_id,title,source,metadata) VALUES($1,$2,$3,$4,$5)',[documentId,userId,title,source||null,metadata||{}]);for(let i=0;i<chunks.length;i++)await c.query('INSERT INTO panthorium_knowledge_chunks(chunk_id,document_id,user_id,chunk_index,content) VALUES($1,$2,$3,$4,$5)',[randomUUID(),documentId,userId,i,chunks[i]]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}else{this.docs.set(documentId,{documentId,userId,title,source:source||null,metadata:metadata||{},createdAt:now,updatedAt:now});this.chunks.set(documentId,chunks.map((content,i)=>({chunkId:randomUUID(),documentId,userId,chunkIndex:i,content,createdAt:now})));}return this.get(userId,documentId); }
  async get(userId,id){if(this.pool){const d=await this.pool.query('SELECT * FROM panthorium_knowledge_documents WHERE user_id=$1 AND document_id=$2',[userId,id]);if(!d.rows[0])return null;const c=await this.pool.query('SELECT * FROM panthorium_knowledge_chunks WHERE user_id=$1 AND document_id=$2 ORDER BY chunk_index',[userId,id]);return {...this.mapDoc(d.rows[0]),chunks:c.rows.map(r=>this.mapChunk(r))};}const d=this.docs.get(id);if(!d||d.userId!==userId)return null;return {...d,chunks:this.chunks.get(id)||[]};}
  async list(userId,limit=50){const n=Math.max(1,Math.min(Number(limit)||50,100));if(this.pool){const r=await this.pool.query('SELECT d.*, (SELECT COUNT(*)::int FROM panthorium_knowledge_chunks c WHERE c.document_id=d.document_id) AS chunk_count FROM panthorium_knowledge_documents d WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2',[userId,n]);return r.rows.map(x=>({...this.mapDoc(x),chunkCount:x.chunk_count}));}return [...this.docs.values()].filter(x=>x.userId===userId).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,n).map(x=>({...x,chunkCount:(this.chunks.get(x.documentId)||[]).length}));}
  async search(userId,query,limit=8){const terms=String(query).toLowerCase().split(/\s+/).filter(x=>x.length>1).slice(0,12);if(!terms.length)return[];let rows;if(this.pool){const r=await this.pool.query('SELECT c.*,d.title,d.source FROM panthorium_knowledge_chunks c JOIN panthorium_knowledge_documents d ON d.document_id=c.document_id WHERE c.user_id=$1 AND c.content ILIKE ANY($2::text[]) LIMIT 100',[userId,terms.map(t=>`%${t}%`)]);rows=r.rows.map(x=>({...this.mapChunk(x),title:x.title,source:x.source}));}else{rows=[];for(const [id,cs] of this.chunks)for(const c of cs){const d=this.docs.get(id);if(d?.userId===userId&&terms.some(t=>c.content.toLowerCase().includes(t)))rows.push({...c,title:d.title,source:d.source});}}return rows.map(x=>({...x,score:terms.reduce((s,t)=>s+(x.content.toLowerCase().includes(t)?1:0),0)})).sort((a,b)=>b.score-a.score).slice(0,Math.max(1,Math.min(Number(limit)||8,20)));}
  async delete(userId,id){if(this.pool){const r=await this.pool.query('DELETE FROM panthorium_knowledge_documents WHERE user_id=$1 AND document_id=$2 RETURNING document_id',[userId,id]);return!!r.rowCount;}const d=this.docs.get(id);if(!d||d.userId!==userId)return false;this.docs.delete(id);this.chunks.delete(id);return true;}
}
module.exports={AgentKnowledgeRepository};
