class AgentKnowledgeService {
 constructor({repository,audit}={}){this.repository=repository;this.audit=audit;} async init(){await this.repository?.init?.();} allowed(user){return!!user?.sub&&!String(user.sub).startsWith('guest:')&&user.permissions?.includes('chat');}
 chunk(text,{size=1400,overlap=180}={}){const clean=String(text||'').replace(/\r/g,'').trim();if(!clean)return[];const out=[];let start=0;while(start<clean.length&&out.length<500){let end=Math.min(clean.length,start+size);if(end<clean.length){const cut=Math.max(clean.lastIndexOf('\n',end),clean.lastIndexOf('. ',end));if(cut>start+size/2)end=cut+1;}out.push(clean.slice(start,end).trim());if(end>=clean.length)break;start=Math.max(start+1,end-overlap);}return out.filter(Boolean);}
 async ingest({user,title,content,source,metadata,requestId}={}){if(!this.allowed(user))return{ok:false,error:'knowledge_requires_account'};const t=String(title||'').trim(),body=String(content||'').trim();if(!t||t.length>240)return{ok:false,error:'invalid_knowledge_title'};if(!body||body.length>500000)return{ok:false,error:'invalid_knowledge_content'};if(source!=null&&(typeof source!=='string'||source.length>500))return{ok:false,error:'invalid_knowledge_source'};if(metadata!=null&&(!metadata||typeof metadata!=='object'||Array.isArray(metadata)||JSON.stringify(metadata).length>8000))return{ok:false,error:'invalid_knowledge_metadata'};const chunks=this.chunk(body);if(!chunks.length)return{ok:false,error:'invalid_knowledge_content'};const document=await this.repository.create({userId:user.sub,title:t,source:source||null,metadata:metadata||{},chunks});this.audit?.record('agent.knowledge_ingested',{userId:user.sub,requestId,documentId:document.documentId,chunks:chunks.length,contentLength:body.length});return{ok:true,document:{...document,chunks:undefined,chunkCount:chunks.length}};}
 async list({user,limit}={}){if(!this.allowed(user))return{ok:false,error:'knowledge_requires_account'};return{ok:true,documents:await this.repository.list(user.sub,limit)};}
 async get({user,documentId}={}){if(!this.allowed(user))return{ok:false,error:'knowledge_requires_account'};if(!/^[0-9a-f-]{36}$/i.test(String(documentId||'')))return{ok:false,error:'invalid_document_id'};const document=await this.repository.get(user.sub,documentId);return document?{ok:true,document}:{ok:false,error:'knowledge_not_found'};}
 async search({user,query,limit=8,requestId}={}){if(!this.allowed(user))return{ok:false,error:'knowledge_requires_account'};const q=String(query||'').trim();if(!q||q.length>500)return{ok:false,error:'invalid_knowledge_query'};const chunks=await this.repository.search(user.sub,q,limit);this.audit?.record('agent.knowledge_searched',{userId:user.sub,requestId,queryLength:q.length,matches:chunks.length});return{ok:true,chunks};}
 async context({user,query,limit=6}={}){const r=await this.search({user,query,limit});if(!r.ok)return r;return{ok:true,context:r.chunks.map(x=>({documentId:x.documentId,chunkId:x.chunkId,title:x.title,source:x.source,content:x.content,score:x.score}))};}
 async remove({user,documentId,requestId}={}){if(!this.allowed(user))return{ok:false,error:'knowledge_requires_account'};if(!/^[0-9a-f-]{36}$/i.test(String(documentId||'')))return{ok:false,error:'invalid_document_id'};const deleted=await this.repository.delete(user.sub,documentId);if(!deleted)return{ok:false,error:'knowledge_not_found'};this.audit?.record('agent.knowledge_deleted',{userId:user.sub,requestId,documentId});return{ok:true};}
}
module.exports={AgentKnowledgeService};
