class AgentAutomationService {
  constructor({ repository, jobs, audit, policy } = {}) { this.repository=repository; this.jobs=jobs; this.audit=audit; this.policy=policy||null; }
  async init(){ await this.repository?.init?.(); }
  userContext(user){ return { sub:user?.sub, username:user?.username||null, roles:Array.isArray(user?.roles)?[...user.roles]:[], permissions:Array.isArray(user?.permissions)?[...user.permissions]:[] }; }
  policyProfile(user){ return this.policy?.profile?.(user) || { tier:'unrestricted', enabled:true, maxSchedules:100, maxTriggers:100, minEveryMinutes:1, maxRuns:1000, canEmitEvents:true }; }
  validateAccount(user){ const sub=String(user?.sub||''); if(!sub||sub.startsWith('guest:'))return{ok:false,error:'automation_requires_account'}; if(!Array.isArray(user?.permissions)||!user.permissions.includes('chat'))return{ok:false,error:'automation_permission_denied'}; return{ok:true}; }
  validateRequest(request){ const text=String(request||'').trim(); return text&&text.length<=8000?{ok:true,text}:{ok:false,error:'invalid_agent_request'}; }
  validateProvider(provider){ if(provider==null)return{ok:true,value:null}; if(typeof provider!=='string'||!provider.trim()||provider.length>40)return{ok:false,error:'invalid_provider'}; return{ok:true,value:provider.toLowerCase()}; }
  validateEventKey(value){ const key=String(value||'').trim(); return /^[A-Za-z0-9._:-]{1,64}$/.test(key)?{ok:true,key}:{ok:false,error:'invalid_event_key'}; }
  validateFirstRun(value){ const t=Date.parse(value); if(!Number.isFinite(t))return{ok:false,error:'invalid_first_run_at'}; if(t<Date.now()+1000)return{ok:false,error:'first_run_must_be_future'}; if(t>Date.now()+366*24*60*60*1000)return{ok:false,error:'first_run_too_far'}; return{ok:true,value:new Date(t).toISOString()}; }
  serializePayload(payload){ if(payload==null)return{ok:true,value:''}; let text; try{text=JSON.stringify(payload);}catch{return{ok:false,error:'invalid_event_payload'};} if(typeof text!=='string')return{ok:false,error:'invalid_event_payload'}; if(text.length>4000)return{ok:false,error:'event_payload_too_large'}; return{ok:true,value:text}; }
  async createSchedule({user,request,provider,firstRunAt,everyMinutes,maxRuns,requestId}={}){
    const account=this.validateAccount(user); if(!account.ok)return account;
    const r=this.validateRequest(request); if(!r.ok)return r; const p=this.validateProvider(provider); if(!p.ok)return p; const f=this.validateFirstRun(firstRunAt); if(!f.ok)return f;
    const every=Number(everyMinutes); if(!Number.isInteger(every)||every<1||every>10080)return{ok:false,error:'invalid_every_minutes'};
    const max=maxRuns==null?null:Number(maxRuns); if(max!=null&&(!Number.isInteger(max)||max<1||max>1000))return{ok:false,error:'invalid_max_runs'};
    if(this.policy?.evaluateSchedule){const decision=await this.policy.evaluateSchedule({user,repository:this.repository,everyMinutes:every,maxRuns:max});if(!decision.ok){this.audit?.record('agent.automation_policy_denied',{userId:user?.sub,requestId,action:'create_schedule',error:decision.error,tier:decision.limits?.tier});return decision;}}
    const item=await this.repository.createSchedule({userId:user?.sub,userContext:this.userContext(user),request:r.text,provider:p.value,everyMinutes:every,nextRunAt:f.value,maxRuns:max});
    this.audit?.record('agent.schedule_created',{userId:user?.sub,requestId,scheduleId:item.scheduleId,everyMinutes:every,nextRunAt:item.nextRunAt,maxRuns:max}); return{ok:true,schedule:item};
  }
  async listSchedules(userId,limit){return this.repository.listSchedules(userId,limit);}
  async disableSchedule({user,scheduleId,requestId}={}){const account=this.validateAccount(user);if(!account.ok)return account;const item=await this.repository.disableSchedule(user?.sub,String(scheduleId||''));if(!item)return{ok:false,error:'agent_schedule_not_found'};this.audit?.record('agent.schedule_disabled',{userId:user?.sub,requestId,scheduleId:item.scheduleId});return{ok:true,schedule:item};}
  async createTrigger({user,eventKey,request,provider,requestId}={}){const account=this.validateAccount(user);if(!account.ok)return account;const e=this.validateEventKey(eventKey);if(!e.ok)return e;const r=this.validateRequest(request);if(!r.ok)return r;const p=this.validateProvider(provider);if(!p.ok)return p;if(this.policy?.evaluateTrigger){const decision=await this.policy.evaluateTrigger({user,repository:this.repository});if(!decision.ok){this.audit?.record('agent.automation_policy_denied',{userId:user?.sub,requestId,action:'create_trigger',error:decision.error,tier:decision.limits?.tier});return decision;}}const item=await this.repository.createTrigger({userId:user?.sub,userContext:this.userContext(user),eventKey:e.key,request:r.text,provider:p.value});this.audit?.record('agent.trigger_created',{userId:user?.sub,requestId,triggerId:item.triggerId,eventKey:item.eventKey});return{ok:true,trigger:item};}
  async listTriggers(userId,limit){return this.repository.listTriggers(userId,limit);}
  async disableTrigger({user,triggerId,requestId}={}){const account=this.validateAccount(user);if(!account.ok)return account;const item=await this.repository.disableTrigger(user?.sub,String(triggerId||''));if(!item)return{ok:false,error:'agent_trigger_not_found'};this.audit?.record('agent.trigger_disabled',{userId:user?.sub,requestId,triggerId:item.triggerId});return{ok:true,trigger:item};}
  async emit({user,eventKey,payload,requestId}={}){const account=this.validateAccount(user);if(!account.ok)return account;if(this.policy?.evaluateEmit){const decision=this.policy.evaluateEmit(user);if(!decision.ok){this.audit?.record('agent.automation_policy_denied',{userId:user?.sub,requestId,action:'emit_event',error:decision.error,tier:decision.limits?.tier});return decision;}}const e=this.validateEventKey(eventKey);if(!e.ok)return e;const encoded=this.serializePayload(payload);if(!encoded.ok)return encoded;const serialized=encoded.value;const triggers=await this.repository.matchingTriggers(user?.sub,e.key,20);const jobs=[];for(const trigger of triggers){const suffix=serialized?`\n\nEvent payload: ${serialized}`:'';const job=await this.jobs.create({userId:trigger.userId,userContext:trigger.userContext,request:`${trigger.request}${suffix}`.slice(0,8000),provider:trigger.provider,runAt:new Date().toISOString(),status:'scheduled',result:{source:'event',eventKey:e.key,triggerId:trigger.triggerId}});jobs.push(job);}this.audit?.record('agent.event_emitted',{userId:user?.sub,requestId,eventKey:e.key,matched:jobs.length});return{ok:true,eventKey:e.key,scheduledJobs:jobs.map(j=>({jobId:j.jobId,runAt:j.runAt}))};}
  async materializeDue(limit=10){const due=await this.repository.claimDueSchedules(limit);const jobs=[];for(const schedule of due){const job=await this.jobs.create({userId:schedule.userId,userContext:schedule.userContext,request:schedule.request,provider:schedule.provider,runAt:new Date().toISOString(),status:'scheduled',result:{source:'schedule',scheduleId:schedule.scheduleId,occurrence:schedule.runCount}});jobs.push(job);this.audit?.record('agent.schedule_fired',{userId:schedule.userId,scheduleId:schedule.scheduleId,jobId:job.jobId,occurrence:schedule.runCount});}return jobs;}
}
module.exports={AgentAutomationService};