const SECRET_KEY_RE=/^PANTHORIUM_INTEGRATION_SECRET_[A-Z0-9_]{1,80}$/;
class IntegrationService {
  constructor({repository,executions,audit,allowedHosts=[],fetcher}={}){this.repository=repository;this.executions=executions||null;this.audit=audit;this.allowedHosts=new Set((allowedHosts||[]).map(x=>String(x).trim().toLowerCase()).filter(Boolean));this.fetcher=fetcher||global.fetch;}
  canManage(user){return!!user?.sub&&!String(user.sub).startsWith('guest:')&&Array.isArray(user.permissions)&&user.permissions.includes('settings');}
  canInvoke(user){return!!user?.sub&&!String(user.sub).startsWith('guest:')&&Array.isArray(user.permissions)&&user.permissions.includes('core:command');}
  validateEndpoint(value){let url;try{url=new URL(String(value||''));}catch{return{ok:false,error:'invalid_integration_endpoint'};}if(url.protocol!=='https:'||url.username||url.password||url.port)return{ok:false,error:'invalid_integration_endpoint'};const host=url.hostname.toLowerCase();if(!this.allowedHosts.has(host))return{ok:false,error:'integration_host_not_allowed'};return{ok:true,url:url.toString(),host};}
  async create({user,name,endpointUrl,secretEnvKey}={}){if(!this.canManage(user))return{ok:false,error:'integration_settings_required'};const safeName=String(name||'').trim();if(!safeName||safeName.length>120)return{ok:false,error:'invalid_integration_name'};const endpoint=this.validateEndpoint(endpointUrl);if(!endpoint.ok)return endpoint;const key=secretEnvKey==null?'':String(secretEnvKey).trim();if(key&&!SECRET_KEY_RE.test(key))return{ok:false,error:'invalid_integration_secret_ref'};const integration=await this.repository.create({ownerUserId:user.sub,name:safeName,kind:'webhook',endpointUrl:endpoint.url,secretEnvKey:key||null});this.audit?.record('integration.created',{userId:user.sub,integrationId:integration.integrationId,host:endpoint.host});return{ok:true,integration};}
  async list(user,limit){if(!this.canManage(user))return{ok:false,error:'integration_settings_required'};return{ok:true,integrations:await this.repository.list(user.sub,limit)};}
  async history(user,{integrationId,limit}={}){if(!this.canManage(user))return{ok:false,error:'integration_settings_required'};if(!this.executions)return{ok:true,executions:[]};return{ok:true,executions:await this.executions.list(user.sub,{integrationId,limit})};}
  async setEnabled({user,integrationId,enabled}={}){if(!this.canManage(user))return{ok:false,error:'integration_settings_required'};const integration=await this.repository.setEnabled(user.sub,integrationId,!!enabled);if(!integration)return{ok:false,error:'integration_not_found'};this.audit?.record('integration.enabled_changed',{userId:user.sub,integrationId,enabled:!!enabled});return{ok:true,integration};}
  async remove({user,integrationId}={}){if(!this.canManage(user))return{ok:false,error:'integration_settings_required'};const removed=await this.repository.remove(user.sub,integrationId);if(!removed)return{ok:false,error:'integration_not_found'};this.audit?.record('integration.deleted',{userId:user.sub,integrationId});return{ok:true,removed:true};}
  async recordExecution(data){try{return this.executions?await this.executions.record(data):null;}catch(error){this.audit?.record('integration.execution_history_failed',{userId:data.ownerUserId,integrationId:data.integrationId,error:error.message});return null;}}
  async invoke({user,integrationId,payload,requestId}={}){if(!this.canInvoke(user))return{ok:false,error:'integration_core_command_required'};const integration=await this.repository.get(user.sub,integrationId);if(!integration)return{ok:false,error:'integration_not_found'};if(!integration.enabled)return{ok:false,error:'integration_disabled'};const endpoint=this.validateEndpoint(integration.endpointUrl);if(!endpoint.ok)return endpoint;if(payload!=null&&(typeof payload!=='object'||Array.isArray(payload)))return{ok:false,error:'invalid_integration_payload'};const body=JSON.stringify(payload||{});if(Buffer.byteLength(body,'utf8')>32768)return{ok:false,error:'integration_payload_too_large'};const headers={'content-type':'application/json','x-panthorium-integration-id':integration.integrationId};if(integration.secretEnvKey){const secret=process.env[integration.secretEnvKey];if(!secret)return{ok:false,error:'integration_secret_unavailable'};headers.authorization=`Bearer ${secret}`;}
    const started=Date.now();this.audit?.record('integration.invoke_started',{userId:user.sub,requestId,integrationId,host:endpoint.host});
    try{const response=await this.fetcher(endpoint.url,{method:'POST',headers,body,signal:AbortSignal.timeout(10000)});const text=await response.text();const durationMs=Date.now()-started;const output={status:response.status,ok:response.ok,body:text.slice(0,4000)};await this.recordExecution({integrationId,ownerUserId:user.sub,requestId,status:response.ok?'completed':'remote_error',httpStatus:response.status,durationMs,errorCode:response.ok?null:'integration_remote_error',responsePreview:text});this.audit?.record('integration.invoke_completed',{userId:user.sub,requestId,integrationId,status:response.status,durationMs});return response.ok?{ok:true,output}:{ok:false,error:'integration_remote_error',output};}catch(error){const durationMs=Date.now()-started;await this.recordExecution({integrationId,ownerUserId:user.sub,requestId,status:'failed',durationMs,errorCode:'integration_request_failed'});this.audit?.record('integration.invoke_failed',{userId:user.sub,requestId,integrationId,error:error.message,durationMs});return{ok:false,error:'integration_request_failed'};}
  }
}
module.exports={IntegrationService,SECRET_KEY_RE};
