const { isIP } = require('node:net');
const dns = require('node:dns').promises;
const https = require('node:https');
const SECRET_KEY_RE=/^PANTHORIUM_INTEGRATION_SECRET_[A-Z0-9_]{1,80}$/;
const RESPONSE_PREVIEW_BYTES=4096;
function isPrivateAddress(address){
  const value=String(address||'').toLowerCase().replace(/\.$/,'');
  if(value.startsWith('::ffff:')){const mapped=value.slice(7);if(isIP(mapped)===4)return isPrivateAddress(mapped);}
  if(isIP(value)===4){
    const p=value.split('.').map(Number);
    return p[0]===0||p[0]===10||p[0]===127||(p[0]===100&&p[1]>=64&&p[1]<=127)||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===0&&p[2]===0)||(p[0]===192&&p[1]===0&&p[2]===2)||(p[0]===192&&p[1]===168)||(p[0]===198&&(p[1]===18||p[1]===19))||(p[0]===198&&p[1]===51&&p[2]===100)||(p[0]===203&&p[1]===0&&p[2]===113)||p[0]>=224;
  }
  if(isIP(value)===6){return value==='::'||value==='::1'||value.startsWith('fc')||value.startsWith('fd')||/^fe[89ab]/.test(value)||value.startsWith('ff')||value.startsWith('2001:db8:')||value==='2001:db8::';}
  return true;
}
function normalizeRecords(records){return (Array.isArray(records)?records:[]).map(record=>{const address=String(record?.address||record||'');return{address,family:Number(record?.family)||isIP(address)};}).filter(record=>record.address&&[4,6].includes(record.family));}
class IntegrationService {
  constructor({repository,executions,audit,allowedHosts=[],fetcher,resolver,httpsModule}={}){this.repository=repository;this.executions=executions||null;this.audit=audit;this.allowedHosts=new Set((allowedHosts||[]).map(x=>String(x).trim().toLowerCase()).filter(Boolean));this.fetcher=fetcher||null;this.resolver=resolver||((host)=>dns.lookup(host,{all:true,verbatim:true}));this.https=httpsModule||https;}
  canManage(user){return!!user?.sub&&!String(user.sub).startsWith('guest:')&&Array.isArray(user.permissions)&&user.permissions.includes('settings');}
  canInvoke(user){return!!user?.sub&&!String(user.sub).startsWith('guest:')&&Array.isArray(user.permissions)&&user.permissions.includes('core:command');}
  validateEndpoint(value){let url;try{url=new URL(String(value||''));}catch{return{ok:false,error:'invalid_integration_endpoint'};}if(url.protocol!=='https:'||url.username||url.password||url.port||url.hash)return{ok:false,error:'invalid_integration_endpoint'};const host=url.hostname.toLowerCase().replace(/\.$/,'');if(isIP(host)||host==='localhost'||host.endsWith('.local')||host.endsWith('.internal'))return{ok:false,error:'integration_host_not_allowed'};if(!this.allowedHosts.has(host))return{ok:false,error:'integration_host_not_allowed'};url.hostname=host;return{ok:true,url:url.toString(),host};}
  async validateDestination(endpoint){try{const records=normalizeRecords(await this.resolver(endpoint.host));if(!records.length)return{ok:false,error:'integration_dns_unavailable'};if(records.some(record=>isPrivateAddress(record.address)))return{ok:false,error:'integration_private_address_blocked'};return{ok:true,records};}catch{return{ok:false,error:'integration_dns_unavailable'};}}
  async create({user,name,endpointUrl,secretEnvKey}={}){if(!this.canManage(user))return{ok:false,error:'integration_settings_required'};const safeName=String(name||'').trim();if(!safeName||safeName.length>120)return{ok:false,error:'invalid_integration_name'};const endpoint=this.validateEndpoint(endpointUrl);if(!endpoint.ok)return endpoint;const key=secretEnvKey==null?'':String(secretEnvKey).trim();if(key&&!SECRET_KEY_RE.test(key))return{ok:false,error:'invalid_integration_secret_ref'};const integration=await this.repository.create({ownerUserId:user.sub,name:safeName,kind:'webhook',endpointUrl:endpoint.url,secretEnvKey:key||null});this.audit?.record('integration.created',{userId:user.sub,integrationId:integration.integrationId,host:endpoint.host});return{ok:true,integration};}
  async list(user,limit){if(!this.canManage(user))return{ok:false,error:'integration_settings_required'};return{ok:true,integrations:await this.repository.list(user.sub,limit)};}
  async history(user,{integrationId,limit}={}){if(!this.canManage(user))return{ok:false,error:'integration_settings_required'};if(!this.executions)return{ok:true,executions:[]};return{ok:true,executions:await this.executions.list(user.sub,{integrationId,limit})};}
  async setEnabled({user,integrationId,enabled}={}){if(!this.canManage(user))return{ok:false,error:'integration_settings_required'};const integration=await this.repository.setEnabled(user.sub,integrationId,!!enabled);if(!integration)return{ok:false,error:'integration_not_found'};this.audit?.record('integration.enabled_changed',{userId:user.sub,integrationId,enabled:!!enabled});return{ok:true,integration};}
  async remove({user,integrationId}={}){if(!this.canManage(user))return{ok:false,error:'integration_settings_required'};const removed=await this.repository.remove(user.sub,integrationId);if(!removed)return{ok:false,error:'integration_not_found'};this.audit?.record('integration.deleted',{userId:user.sub,integrationId});return{ok:true,removed:true};}
  async recordExecution(data){try{return this.executions?await this.executions.record(data):null;}catch(error){this.audit?.record('integration.execution_history_failed',{userId:data.ownerUserId,integrationId:data.integrationId,error:error.message});return null;}}
  async postPinned(endpoint,destination,headers,body){const selected=destination.records[0];return new Promise((resolve,reject)=>{const url=new URL(endpoint.url);let settled=false;const finish=(fn,value)=>{if(settled)return;settled=true;fn(value);};const req=this.https.request({protocol:'https:',hostname:endpoint.host,servername:endpoint.host,path:`${url.pathname}${url.search}`,method:'POST',headers:{...headers,'content-length':Buffer.byteLength(body,'utf8')},lookup:(hostname,options,callback)=>callback(null,selected.address,selected.family),timeout:10000},res=>{let preview='';res.setEncoding('utf8');res.on('data',chunk=>{if(Buffer.byteLength(preview,'utf8')<RESPONSE_PREVIEW_BYTES)preview=(preview+chunk).slice(0,RESPONSE_PREVIEW_BYTES);});res.on('end',()=>finish(resolve,{ok:res.statusCode>=200&&res.statusCode<300,status:res.statusCode||0,text:preview}));res.on('error',error=>finish(reject,error));});req.on('timeout',()=>req.destroy(new Error('integration_timeout')));req.on('error',error=>finish(reject,error));req.end(body);});}
  async send(endpoint,destination,headers,body){if(this.fetcher){const response=await this.fetcher(endpoint.url,{method:'POST',headers,body,redirect:'error',signal:AbortSignal.timeout(10000)});const text=await response.text();return{ok:!!response.ok,status:Number(response.status)||0,text:String(text||'').slice(0,RESPONSE_PREVIEW_BYTES)};}return this.postPinned(endpoint,destination,headers,body);}
  async invoke({user,integrationId,payload,requestId}={}){if(!this.canInvoke(user))return{ok:false,error:'integration_core_command_required'};const integration=await this.repository.get(user.sub,integrationId);if(!integration)return{ok:false,error:'integration_not_found'};if(!integration.enabled)return{ok:false,error:'integration_disabled'};const endpoint=this.validateEndpoint(integration.endpointUrl);if(!endpoint.ok)return endpoint;const destination=await this.validateDestination(endpoint);if(!destination.ok){this.audit?.record('integration.destination_blocked',{userId:user.sub,requestId,integrationId,host:endpoint.host,error:destination.error});return destination;}if(payload!=null&&(typeof payload!=='object'||Array.isArray(payload)))return{ok:false,error:'invalid_integration_payload'};let body;try{body=JSON.stringify(payload||{});}catch{return{ok:false,error:'invalid_integration_payload'};}if(Buffer.byteLength(body,'utf8')>32768)return{ok:false,error:'integration_payload_too_large'};const headers={'content-type':'application/json','x-panthorium-integration-id':integration.integrationId};if(integration.secretEnvKey){const secret=process.env[integration.secretEnvKey];if(!secret)return{ok:false,error:'integration_secret_unavailable'};headers.authorization=`Bearer ${secret}`;}
    const started=Date.now();this.audit?.record('integration.invoke_started',{userId:user.sub,requestId,integrationId,host:endpoint.host,destination:selectedAddress(destination)});
    try{const response=await this.send(endpoint,destination,headers,body);const durationMs=Date.now()-started;const output={status:response.status,ok:response.ok,body:response.text};await this.recordExecution({integrationId,ownerUserId:user.sub,requestId,status:response.ok?'completed':'remote_error',httpStatus:response.status,durationMs,errorCode:response.ok?null:'integration_remote_error',responsePreview:response.text});this.audit?.record('integration.invoke_completed',{userId:user.sub,requestId,integrationId,status:response.status,durationMs});return response.ok?{ok:true,output}:{ok:false,error:'integration_remote_error',output};}catch(error){const durationMs=Date.now()-started;await this.recordExecution({integrationId,ownerUserId:user.sub,requestId,status:'failed',durationMs,errorCode:'integration_request_failed'});this.audit?.record('integration.invoke_failed',{userId:user.sub,requestId,integrationId,error:String(error?.message||'request_failed').slice(0,160),durationMs});return{ok:false,error:'integration_request_failed'};}
  }
}
function selectedAddress(destination){return destination?.records?.[0]?.address||null;}
module.exports={IntegrationService,SECRET_KEY_RE,isPrivateAddress,normalizeRecords,RESPONSE_PREVIEW_BYTES};
