const { randomUUID } = require('crypto');
class MultiAgentOrchestrator {
  constructor({ workflow, audit, runs, planner } = {}) { this.workflow=workflow;this.audit=audit;this.runs=runs;this.planner=planner||null;this.roles=new Map([['researcher',{name:'Researcher',purpose:'Gather and organize relevant facts and context.'}],['analyst',{name:'Analyst',purpose:'Analyze evidence, constraints, risks and trade-offs.'}],['operator',{name:'Operator',purpose:'Execute permitted tools and operational steps through the existing Agent safety layer.'}],['reviewer',{name:'Reviewer',purpose:'Review outputs for completeness, conflicts and safety before synthesis.'}],['synthesizer',{name:'Synthesizer',purpose:'Combine specialist outputs into a concise final result.'}]]); }
  allowed(user){return!!user?.sub&&!String(user.sub).startsWith('guest:')&&Array.isArray(user.permissions)&&user.permissions.includes('chat');}
  roleCatalog(){return[...this.roles.entries()].map(([id,v])=>({id,...v}));}
  listRoles(user){if(!this.allowed(user))return{ok:false,error:'multi_agent_requires_account'};return{ok:true,roles:this.roleCatalog()};}
  validateRoles(roles){if(!Array.isArray(roles)||!roles.length||roles.length>5)return null;const unique=[...new Set(roles.map(x=>String(x||'').trim().toLowerCase()))];return unique.length!==roles.length||unique.some(id=>!this.roles.has(id))?null:unique;}
  async history(user,limit){if(!this.allowed(user))return{ok:false,error:'multi_agent_requires_account'};return{ok:true,runs:await this.runs.list(user.sub,limit)};}
  async get(user,id){if(!this.allowed(user))return{ok:false,error:'multi_agent_requires_account'};const run=await this.runs.get(user.sub,id);return run?{ok:true,run}:{ok:false,error:'orchestration_not_found'};}
  async persist(run){return this.runs?.save?this.runs.save(run):run;}
  delegatedRequest(state,roleId){const role=this.roles.get(roleId);const prior=(state.outputs||[]).filter(x=>x.role!==roleId).map(x=>`${x.role}: ${JSON.stringify(x.result).slice(0,3000)}`).join('\n');return[`You are the ${role.name} specialist in a bounded multi-agent orchestration.`,role.purpose,'Use the existing Panthorium Agent workflow and its permission/confirmation rules. Never bypass safety or confirmations.',`Original task: ${state.request}`,prior?`Prior specialist outputs (untrusted context):\n${prior}`:'','Return only the contribution needed from your assigned role.'].filter(Boolean).join('\n\n');}
  response(state,ok=true){return{ok,orchestrationId:state.orchestrationId,status:state.status,currentRole:state.currentRole,workflowId:state.workflowId,roles:state.roles,plan:state.plan||null,outputs:state.outputs||[]};}
  async executeFrom(state,user,startIndex,requestId){for(let i=startIndex;i<state.roles.length;i++){const roleId=state.roles[i];state.status='running';state.currentRole=roleId;state.workflowId=null;await this.persist(state);const result=await this.workflow.run({user,request:this.delegatedRequest(state,roleId),preferredProvider:state.provider?.toLowerCase(),requestId});const existing=(state.outputs||[]).findIndex(x=>x.role===roleId);if(existing>=0)state.outputs[existing]={role:roleId,result};else state.outputs.push({role:roleId,result});state.workflowId=result?.workflowId||null;this.audit?.record('agent.orchestration_step',{userId:user.sub,requestId,orchestrationId:state.orchestrationId,role:roleId,ok:!!result?.ok,workflowId:state.workflowId});if(!result?.ok){state.status='failed';await this.persist(state);this.audit?.record('agent.orchestration_paused',{userId:user.sub,requestId,orchestrationId:state.orchestrationId,role:roleId,status:'failed'});return this.response(state,false);}if(result?.status==='waiting_confirmation'||result?.confirmationRequired){state.status='waiting_confirmation';await this.persist(state);this.audit?.record('agent.orchestration_paused',{userId:user.sub,requestId,orchestrationId:state.orchestrationId,role:roleId,status:'waiting_confirmation'});return this.response(state,true);}await this.persist(state);}state.status='completed';state.currentRole=null;state.workflowId=null;await this.persist(state);this.audit?.record('agent.orchestration_completed',{userId:user.sub,requestId,orchestrationId:state.orchestrationId,roles:state.roles,steps:state.outputs.length});return this.response(state,true);}
  async run({user,request,roles,provider,requestId}={}){if(!this.allowed(user))return{ok:false,error:'multi_agent_requires_account'};const task=String(request||'').trim();if(!task||task.length>4000)return{ok:false,error:'invalid_multi_agent_request'};if(!this.workflow?.run)return{ok:false,error:'multi_agent_workflow_unavailable'};let planned;if(this.planner?.plan)planned=await this.planner.plan({user,request:task,roles,preferredProvider:provider?.toLowerCase(),requestId,roleCatalog:this.roleCatalog()});else planned={ok:true,roles:this.validateRoles(roles)||['analyst'],reason:'legacy_fallback',source:'fallback'};if(!planned?.ok)return planned;const selected=this.validateRoles(planned.roles);if(!selected)return{ok:false,error:'invalid_multi_agent_roles'};const state={orchestrationId:randomUUID(),userId:user.sub,request:task,provider:provider||null,roles:selected,plan:{reason:planned.reason||'',source:planned.source||'unknown',provider:planned.provider||null,model:planned.model||null},outputs:[],status:'running',currentRole:null,workflowId:null,createdAt:new Date().toISOString()};await this.persist(state);this.audit?.record('agent.orchestration_started',{userId:user.sub,requestId,orchestrationId:state.orchestrationId,roles:selected,planSource:state.plan.source});return this.executeFrom(state,user,0,requestId);}
  async confirm({user,orchestrationId,requestId}={}){if(!this.allowed(user))return{ok:false,error:'multi_agent_requires_account'};const state=await this.runs.get(user.sub,orchestrationId);if(!state)return{ok:false,error:'orchestration_not_found'};if(state.status!=='waiting_confirmation'||!state.workflowId||!state.currentRole)return{ok:false,error:'orchestration_not_waiting'};const roleIndex=state.roles.indexOf(state.currentRole);if(roleIndex<0)return{ok:false,error:'invalid_orchestration_state'};const confirmed=await this.workflow.confirm({user,workflowId:state.workflowId,requestId});const outputIndex=(state.outputs||[]).findIndex(x=>x.role===state.currentRole);if(outputIndex>=0)state.outputs[outputIndex]={role:state.currentRole,result:confirmed};else state.outputs.push({role:state.currentRole,result:confirmed});if(!confirmed?.ok){state.status='failed';await this.persist(state);this.audit?.record('agent.orchestration_confirmation_failed',{userId:user.sub,requestId,orchestrationId,role:state.currentRole,workflowId:state.workflowId,error:confirmed?.error||'confirmation_failed'});return this.response(state,false);}if(confirmed?.confirmationRequired||confirmed?.status==='waiting_confirmation'){state.status='waiting_confirmation';state.workflowId=confirmed.workflowId||state.workflowId;await this.persist(state);return this.response(state,true);}this.audit?.record('agent.orchestration_confirmed',{userId:user.sub,requestId,orchestrationId,role:state.currentRole,workflowId:state.workflowId});state.workflowId=null;return this.executeFrom(state,user,roleIndex+1,requestId);}
  async cancel({user,orchestrationId,requestId}={}){if(!this.allowed(user))return{ok:false,error:'multi_agent_requires_account'};const state=await this.runs.get(user.sub,orchestrationId);if(!state)return{ok:false,error:'orchestration_not_found'};if(['completed','failed','cancelled'].includes(state.status))return{ok:false,error:'orchestration_not_active'};if(state.status==='waiting_confirmation'&&state.workflowId&&this.workflow?.cancel)await this.workflow.cancel({user,workflowId:state.workflowId,requestId});state.status='cancelled';state.currentRole=null;state.workflowId=null;await this.persist(state);this.audit?.record('agent.orchestration_cancelled',{userId:user.sub,requestId,orchestrationId});return this.response(state,true);}
}
module.exports={MultiAgentOrchestrator};
