const {AutonomousLearningPolicy}=require('./autonomousLearningPolicy');

class SentinelLearningOrchestrator{
  constructor({repository,trainingRepository,audit,policy=new AutonomousLearningPolicy(),shadowEvaluator,recovery=null}={}){this.repository=repository;this.trainingRepository=trainingRepository;this.audit=audit;this.policy=policy;this.shadowEvaluator=shadowEvaluator;this.recovery=recovery;}
  async init(){await this.repository.init();}
  riskFor(example){const text=`${example.prompt||''}\n${example.answer||''}`.toLowerCase();const protectedHit=this.policy.protectedDomains.some(d=>text.includes(d.replaceAll('_',' '))||text.includes(d));return protectedHit?'protected':'normal';}
  async exampleFor(exampleId){return(await this.trainingRepository.list({limit:500})).find(x=>x.exampleId===exampleId)||null;}
  async quarantine(example){await this.init();const risk=this.riskFor(example);const judges=example.evaluation?.judges||[];const consensus=judges.length?Math.round((judges.filter(j=>j.safe&&j.correct&&j.relevant).length/judges.length)*100):0;const version=await this.repository.create({exampleId:example.exampleId,state:'quarantined',score:example.qualityScore,risk,metadata:{source:example.source,provider:example.provider,model:example.model,fingerprint:example.fingerprint,evaluatorConsensus:consensus,reviewers:judges.map(j=>j.provider)}});await this.repository.event(version.versionId,'quarantined',{risk,consensus});this.audit?.record('sentinel.learning_quarantined',{versionId:version.versionId,exampleId:example.exampleId,risk,consensus});return version;}
  async evaluateForShadow(version,example){const evaluation=example.evaluation||{};const judges=Array.isArray(evaluation.judges)?evaluation.judges:[];const decision=this.policy.promotionDecision({score:example.qualityScore,safe:evaluation.safe===true,reviewers:judges.map(j=>j.provider),risk:version.risk,shadowSamples:0,shadowScore:null,regressionPct:0});if(!decision.ok&&decision.reasons.some(r=>['protected_domain','unsafe_evaluation','score_below_threshold','insufficient_reviewers'].includes(r))){const rejected=await this.repository.update(version.versionId,{state:'rejected',score:example.qualityScore,metadata:{...version.metadata,gate:decision}});await this.repository.event(version.versionId,'risk_gate_rejected',{decision});return rejected;}const shadow=await this.repository.update(version.versionId,{state:'shadow',score:example.qualityScore,baselineScore:example.qualityScore,metadata:{...version.metadata,gate:decision}});await this.repository.event(version.versionId,'shadow_started',{baselineScore:example.qualityScore});return shadow;}
  async recordShadow(versionId,{score,safe=true,criticalSafetyEvent=false,metadata={}}={}){const v=await this.repository.get(versionId);if(!v||v.state!=='shadow')return{ok:false,error:'learning_version_not_in_shadow'};const sampleScore=Math.max(0,Math.min(100,Math.round(Number(score)||0)));const count=v.shadowSamples+1;const aggregate=Math.round((((v.shadowScore||0)*v.shadowSamples)+sampleScore)/count);const regressionPct=v.baselineScore==null?0:Math.max(0,v.baselineScore-aggregate);const next=await this.repository.update(versionId,{shadowSamples:count,shadowScore:aggregate,metadata:{...v.metadata,lastShadow:{safe,criticalSafetyEvent,regressionPct,...metadata},regressionPct}});await this.repository.event(versionId,'shadow_sample',{score:sampleScore,safe,criticalSafetyEvent,aggregate,regressionPct});if(criticalSafetyEvent||!safe)return this.rollback(versionId,{reason:'shadow_safety_event',autoRecover:true});return{ok:true,version:next,regressionPct};}
  async promoteIfReady(versionId){const v=await this.repository.get(versionId);if(!v||v.state!=='shadow')return{ok:false,error:'learning_version_not_in_shadow'};const example=await this.exampleFor(v.exampleId);if(!example)return{ok:false,error:'training_example_not_found'};const judges=example.evaluation?.judges||[];const regressionPct=v.baselineScore==null?0:Math.max(0,v.baselineScore-(v.shadowScore||0));const decision=this.policy.promotionDecision({score:example.qualityScore,safe:example.evaluation?.safe===true,reviewers:judges.map(j=>j.provider),risk:v.risk,shadowSamples:v.shadowSamples,shadowScore:v.shadowScore,regressionPct});if(!decision.ok)return{ok:true,promoted:false,decision,version:v};const promoted=await this.repository.update(versionId,{state:'active',promotedAt:new Date().toISOString(),metadata:{...v.metadata,promotion:decision,regressionPct}});await this.repository.event(versionId,'promoted',{decision,regressionPct});this.audit?.record('sentinel.learning_promoted',{versionId,exampleId:v.exampleId,score:v.score,shadowScore:v.shadowScore,regressionPct});return{ok:true,promoted:true,decision,version:promoted};}
  async monitor(versionId,{rollingScore,baselineScore,criticalSafetyEvent=false}={}){const v=await this.repository.get(versionId);if(!v||v.state!=='active')return{ok:false,error:'learning_version_not_active'};const baseline=Number.isFinite(Number(baselineScore))?Number(baselineScore):v.baselineScore;const decision=this.policy.rollbackDecision({rollingScore,baselineScore:baseline,criticalSafetyEvent});const regressionPct=Number.isFinite(Number(rollingScore))&&Number.isFinite(Number(baseline))?Math.max(0,Number(baseline)-Number(rollingScore)):0;await this.repository.update(versionId,{metadata:{...v.metadata,lastMonitor:{rollingScore,baselineScore:baseline,criticalSafetyEvent,regressionPct,decision,at:new Date().toISOString()},regressionPct}});await this.repository.event(versionId,'production_monitor',{rollingScore,baselineScore:baseline,criticalSafetyEvent,regressionPct,decision});if(decision.rollback)return this.rollback(versionId,{reason:decision.reason,autoRecover:true});return{ok:true,rollback:false,decision,regressionPct};}
  async rollback(versionId,{reason='automatic_rollback',autoRecover=false}={}){const v=await this.repository.get(versionId);if(!v)return{ok:false,error:'learning_version_not_found'};if(v.state==='rolled_back')return{ok:true,rollback:true,idempotent:true,reason:v.metadata?.rollbackReason||reason,version:v};const rolled=await this.repository.update(versionId,{state:'rolled_back',retiredAt:new Date().toISOString(),metadata:{...v.metadata,rollbackReason:reason,rollbackAt:new Date().toISOString(),automaticRecoveryScheduled:Boolean(autoRecover)}});await this.repository.event(versionId,'rolled_back',{reason,autoRecover});this.audit?.record('sentinel.learning_rolled_back',{versionId,exampleId:v.exampleId,reason,autoRecover});if(autoRecover&&this.recovery?.recoverSoon)this.recovery.recoverSoon(versionId,{reason});return{ok:true,rollback:true,reason,version:rolled,recoveryScheduled:Boolean(autoRecover&&this.recovery)};}
  async recover(versionId){if(!this.recovery)return{ok:false,error:'automatic_recovery_unavailable'};return this.recovery.recover(versionId,{reason:'administrator_requested_recovery'});}
  async status(){const versions=await this.repository.list({limit:500});const events=await this.repository.recentEvents(80);const counts={quarantined:0,shadow:0,active:0,rejected:0,rolled_back:0};for(const v of versions)counts[v.state]=(counts[v.state]||0)+1;const active=versions.filter(v=>v.state==='active');const shadow=versions.filter(v=>v.state==='shadow');const average=(items,key)=>items.length?Math.round(items.reduce((s,x)=>s+Number(x[key]||0),0)/items.length):0;return{ok:true,counts,total:versions.length,metrics:{activeAverageScore:average(active,'score'),shadowAverageScore:average(shadow,'shadowScore'),averageConsensus:versions.length?Math.round(versions.reduce((s,v)=>s+Number(v.metadata?.evaluatorConsensus||0),0)/versions.length):0,recoveryPending:versions.filter(v=>v.state==='rolled_back'&&v.metadata?.automaticRecoveryScheduled).length},policy:{promotionScore:this.policy.promotionScore,shadowMinSamples:this.policy.shadowMinSamples,shadowScore:this.policy.shadowScore,maxRegressionPct:this.policy.maxRegressionPct,rollbackScore:this.policy.rollbackScore},events};}
}
module.exports={SentinelLearningOrchestrator};
