const {AutonomousLearningPolicy}=require('./autonomousLearningPolicy');

class SentinelLearningOrchestrator{
  constructor({repository,trainingRepository,audit,policy=new AutonomousLearningPolicy(),shadowEvaluator}={}){this.repository=repository;this.trainingRepository=trainingRepository;this.audit=audit;this.policy=policy;this.shadowEvaluator=shadowEvaluator;}
  async init(){await this.repository.init();}
  riskFor(example){const text=`${example.prompt||''}\n${example.answer||''}`.toLowerCase();const protectedHit=this.policy.protectedDomains.some(d=>text.includes(d.replaceAll('_',' '))||text.includes(d));return protectedHit?'protected':'normal';}
  async quarantine(example){await this.init();const risk=this.riskFor(example);const version=await this.repository.create({exampleId:example.exampleId,state:'quarantined',score:example.qualityScore,risk,metadata:{source:example.source,provider:example.provider,model:example.model,fingerprint:example.fingerprint}});await this.repository.event(version.versionId,'quarantined',{risk});this.audit?.record('sentinel.learning_quarantined',{versionId:version.versionId,exampleId:example.exampleId,risk});return version;}
  async evaluateForShadow(version,example){const evaluation=example.evaluation||{};const judges=Array.isArray(evaluation.judges)?evaluation.judges:[];const decision=this.policy.promotionDecision({score:example.qualityScore,safe:evaluation.safe===true,reviewers:judges.map(j=>j.provider),risk:version.risk,shadowSamples:0,shadowScore:null,regressionPct:0});if(!decision.ok&&decision.reasons.some(r=>['protected_domain','unsafe_evaluation','score_below_threshold','insufficient_reviewers'].includes(r))){const rejected=await this.repository.update(version.versionId,{state:'rejected',score:example.qualityScore,metadata:{...version.metadata,gate:decision}});await this.repository.event(version.versionId,'risk_gate_rejected',{decision});return rejected;}const shadow=await this.repository.update(version.versionId,{state:'shadow',score:example.qualityScore,metadata:{...version.metadata,gate:decision}});await this.repository.event(version.versionId,'shadow_started',{});return shadow;}
  async recordShadow(versionId,{score,safe=true,criticalSafetyEvent=false,metadata={}}={}){const v=await this.repository.get(versionId);if(!v||v.state!=='shadow')return{ok:false,error:'learning_version_not_in_shadow'};const sampleScore=Math.max(0,Math.min(100,Math.round(Number(score)||0)));const count=v.shadowSamples+1;const aggregate=Math.round((((v.shadowScore||0)*v.shadowSamples)+sampleScore)/count);const next=await this.repository.update(versionId,{shadowSamples:count,shadowScore:aggregate,metadata:{...v.metadata,lastShadow:{safe,criticalSafetyEvent,...metadata}}});await this.repository.event(versionId,'shadow_sample',{score:sampleScore,safe,criticalSafetyEvent});if(criticalSafetyEvent||!safe)return this.rollback(versionId,{reason:'shadow_safety_event'});return{ok:true,version:next};}
  async promoteIfReady(versionId){const v=await this.repository.get(versionId);if(!v||v.state!=='shadow')return{ok:false,error:'learning_version_not_in_shadow'};const example=(await this.trainingRepository.list({limit:500})).find(x=>x.exampleId===v.exampleId);if(!example)return{ok:false,error:'training_example_not_found'};const judges=example.evaluation?.judges||[];const regressionPct=v.baselineScore==null?0:Math.max(0,v.baselineScore-(v.shadowScore||0));const decision=this.policy.promotionDecision({score:example.qualityScore,safe:example.evaluation?.safe===true,reviewers:judges.map(j=>j.provider),risk:v.risk,shadowSamples:v.shadowSamples,shadowScore:v.shadowScore,regressionPct});if(!decision.ok)return{ok:true,promoted:false,decision,version:v};const promoted=await this.repository.update(versionId,{state:'active',promotedAt:new Date().toISOString(),metadata:{...v.metadata,promotion:decision}});await this.repository.event(versionId,'promoted',{decision});this.audit?.record('sentinel.learning_promoted',{versionId,exampleId:v.exampleId,score:v.score,shadowScore:v.shadowScore});return{ok:true,promoted:true,decision,version:promoted};}
  async monitor(versionId,{rollingScore,baselineScore,criticalSafetyEvent=false}={}){const v=await this.repository.get(versionId);if(!v||v.state!=='active')return{ok:false,error:'learning_version_not_active'};const decision=this.policy.rollbackDecision({rollingScore,baselineScore,criticalSafetyEvent});await this.repository.event(versionId,'production_monitor',{rollingScore,baselineScore,criticalSafetyEvent,decision});if(decision.rollback)return this.rollback(versionId,{reason:decision.reason});return{ok:true,rollback:false,decision};}
  async rollback(versionId,{reason='automatic_rollback'}={}){const v=await this.repository.get(versionId);if(!v)return{ok:false,error:'learning_version_not_found'};const rolled=await this.repository.update(versionId,{state:'rolled_back',retiredAt:new Date().toISOString(),metadata:{...v.metadata,rollbackReason:reason}});await this.repository.event(versionId,'rolled_back',{reason});this.audit?.record('sentinel.learning_rolled_back',{versionId,exampleId:v.exampleId,reason});return{ok:true,rollback:true,reason,version:rolled};}
  async status(){const versions=await this.repository.list({limit:500});const events=await this.repository.recentEvents(50);const counts={quarantined:0,shadow:0,active:0,rejected:0,rolled_back:0};for(const v of versions)counts[v.state]=(counts[v.state]||0)+1;return{ok:true,counts,total:versions.length,policy:{promotionScore:this.policy.promotionScore,shadowMinSamples:this.policy.shadowMinSamples,shadowScore:this.policy.shadowScore,maxRegressionPct:this.policy.maxRegressionPct},events};}
}
module.exports={SentinelLearningOrchestrator};